# Generated by Django 5.1 on 2026-08-27 16:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsommationJournaliere",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("jour", models.DateField(unique=True)),
                ("nb_conversations", models.IntegerField(default=0)),
                ("nb_messages", models.IntegerField(default=0)),
                ("jetons_entree", models.BigIntegerField(default=0)),
                ("jetons_sortie", models.BigIntegerField(default=0)),
                ("jetons_cache_lecture", models.BigIntegerField(default=0)),
                ("jetons_cache_ecriture", models.BigIntegerField(default=0)),
                (
                    "cout_fcfa",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
            ],
            options={
                "verbose_name": "Consommation journalière",
                "verbose_name_plural": "Consommations journalières",
                "ordering": ["-jour"],
            },
        ),
        migrations.RemoveIndex(
            model_name="conversation",
            name="assistant_c_tenant__3bc01d_idx",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="utilisateur",
        ),
        migrations.RemoveField(
            model_name="message",
            name="jetons_cache",
        ),
        migrations.RemoveField(
            model_name="message",
            name="tenant",
        ),
        migrations.AddField(
            model_name="conversation",
            name="cle_visiteur",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="conversation",
            name="close",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conversation",
            name="origine",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="message",
            name="cout_fcfa",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="message",
            name="jetons_cache_ecriture",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="message",
            name="jetons_cache_lecture",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[("user", "Visiteur"), ("assistant", "SAMA")], max_length=10
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["cle_visiteur", "-created_at"],
                name="assistant_c_cle_vis_d9b24e_idx",
            ),
        ),
    ]
