# Generated by Django 5.1 on 2026-08-27 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0002_consommationjournaliere_and_more"),
        ("prospects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="prospect",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="prospects.prospect",
            ),
        ),
    ]
