# Generated by Django 5.1 on 2026-05-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_migrate_old_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrateur'), ('ADMIN_ECOLE', 'Administrateur École'), ('ADMIN_RH', 'Responsable RH'), ('ADMIN_COMPTABLE', 'Responsable Comptable'), ('ADMIN_SCOLARITE', 'Responsable Scolarité'), ('LECTEUR', 'Lecteur')], default='LECTEUR', max_length=20),
        ),
    ]
