# Generated by Django 5.1 on 2026-09-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="modules_autorises",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
