# Generated by Django 5.1 on 2026-04-29 15:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matricule', models.CharField(blank=True, max_length=20)),
                ('nom_complet', models.CharField(max_length=200)),
                ('type_employe', models.CharField(choices=[('ENSEIGNANT', 'Enseignant'), ('ADMINISTRATION', 'Administration'), ('APPUI', "Personnel d'appui")], max_length=20)),
                ('poste', models.CharField(max_length=100)),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('VACATAIRE', 'Vacataire'), ('STAGIAIRE', 'Stagiaire')], default='CDI', max_length=20)),
                ('date_embauche', models.DateField()),
                ('date_fin_contrat', models.DateField(blank=True, null=True)),
                ('salaire_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('CONGE', 'En congé'), ('SUSPENDU', 'Suspendu'), ('QUITTE', 'A quitté')], default='ACTIF', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'employes',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='Paie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mois', models.CharField(max_length=7)),
                ('salaire_brut', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ipres', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('css', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ir', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('autres_retenues', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salaire_net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(default='PAYE', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paies', to='rh.employe')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'paies',
                'ordering': ['-mois'],
                'unique_together': {('tenant', 'employe', 'mois')},
            },
        ),
    ]
