# Generated by Django 5.1 on 2026-06-19 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_rh_paie_syscohada'),
        ('tenants', '0004_tenant_regime_paie'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='autorisation_autorite',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='employe',
            name='autorisation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='autorisation_numero',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employe',
            name='autorisation_obs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='avancesalaire',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='bulletinpaie',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=15),
        ),
        migrations.AlterField(
            model_name='bulletinpaie',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
    ]
