# Generated by Django 5.1 on 2026-07-24 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gouvernance", "0006_alter_piecejustificative_objet_type"),
        ("rh", "0003_employe_autorisation_autorite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="avancesalaire",
            name="modes_reglement",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="avancesalaire",
            name="projet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avances_salaire",
                to="gouvernance.projet",
            ),
        ),
        migrations.AddField(
            model_name="avancesalaire",
            name="ressource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avances_salaire",
                to="gouvernance.ressource",
            ),
        ),
        migrations.AddField(
            model_name="bulletinpaie",
            name="modes_reglement",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="bulletinpaie",
            name="projet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bulletins_paie",
                to="gouvernance.projet",
            ),
        ),
        migrations.AddField(
            model_name="bulletinpaie",
            name="ressource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bulletins_paie",
                to="gouvernance.ressource",
            ),
        ),
    ]
