# Generated by Django 5.1 on 2026-07-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0004_avancesalaire_modes_reglement_avancesalaire_projet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employe",
            name="type_contrat",
            field=models.CharField(
                choices=[
                    ("CDI", "CDI"),
                    ("CDD", "CDD"),
                    ("VACATAIRE", "Vacataire"),
                    ("STAGIAIRE", "Stagiaire"),
                    ("PRESTATAIRE", "Prestataire"),
                ],
                default="CDI",
                max_length=20,
            ),
        ),
    ]
