# Generated by Django 5.1 on 2026-07-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0005_alter_employe_type_contrat"),
    ]

    operations = [
        migrations.AddField(
            model_name="avancesalaire",
            name="montant_impute",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="bulletinpaie",
            name="avances_imputees",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
