# Generated by Django 5.1 on 2026-09-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gouvernance", "0006_alter_piecejustificative_objet_type"),
        ("rh", "0006_avancesalaire_montant_impute_and_more"),
        ("tenants", "0012_tenant_anciennete_renouvellement_mois"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bulletinpaie",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="bulletinpaie",
            constraint=models.UniqueConstraint(
                condition=models.Q(("statut", "ANNULE"), _negated=True),
                fields=("tenant", "employe", "mois", "annee"),
                name="uniq_bulletin_actif_par_mois",
            ),
        ),
    ]
