# Generated by Django 5.1 on 2026-09-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0007_bulletin_annule_libere_periode"),
    ]

    operations = [
        migrations.AddField(
            model_name="employe",
            name="date_depart",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employe",
            name="motif_depart",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
