# Generated by Django 5.1 on 2026-09-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0008_employe_depart"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulletinpaie",
            name="nb_heures_retard",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="bulletinpaie",
            name="nb_jours_absence",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="bulletinpaie",
            name="note_remuneration",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="bulletinpaie",
            name="retenue_absence",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
