# Generated by Django 5.1 on 2026-07-02 19:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_tenant_nb_periodes_alter_tenant_periode_scolaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='NattCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=200)),
                ('organisateur', models.CharField(blank=True, default='', max_length=200)),
                ('type_organisateur', models.CharField(choices=[('ASSOCIATION', 'Association'), ('PARTICULIER', 'Particulier'), ('GROUPEMENT', 'Groupement'), ('ENTREPRISE', 'Entreprise'), ('AUTRE', 'Autre')], default='AUTRE', max_length=15)),
                ('coordonnees', models.TextField(blank=True, default='')),
                ('nb_participants', models.IntegerField(default=0)),
                ('duree', models.IntegerField(help_text="Nombre d'échéances du cycle")),
                ('periodicite', models.CharField(choices=[('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUELLE', 'Mensuelle'), ('TRIMESTRIELLE', 'Trimestrielle')], default='MENSUELLE', max_length=15)),
                ('montant_cotisation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mode_attribution', models.CharField(choices=[('TIRAGE', 'Tirage au sort'), ('ORDRE', 'Ordre prédéfini'), ('CONSENSUS', 'Consensus'), ('AUTRE', 'Autre')], default='TIRAGE', max_length=12)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('compte_tresorerie', models.CharField(default='571', max_length=10)),
                ('compte_creance', models.CharField(default='4718', max_length=10)),
                ('compte_dette', models.CharField(default='4798', max_length=10)),
                ('devise', models.CharField(default='XOF', max_length=5)),
                ('observations', models.TextField(blank=True, default='')),
                ('documents', models.JSONField(blank=True, default=list)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('CLOTURE', 'Clôturé'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'gmrf_natt_cycles',
                'ordering': ['-date_debut', 'reference'],
                'unique_together': {('tenant', 'reference')},
            },
        ),
        migrations.CreateModel(
            name='NattReception',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_echeance', models.IntegerField(help_text='Échéance à laquelle la cagnotte est perçue')),
                ('date_reception', models.DateField()),
                ('montant_recu', models.DecimalField(decimal_places=2, max_digits=15)),
                ('compte_tresorerie', models.CharField(default='571', max_length=10)),
                ('montant_creance_soldee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_dette', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observations', models.TextField(blank=True, default='')),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reception', to='gmrf.nattcycle')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'gmrf_natt_receptions',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.CreateModel(
            name='TypeFinancement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('libelle', models.CharField(max_length=150)),
                ('categorie', models.CharField(choices=[('DON', 'Don'), ('SUBV_INVEST', "Subvention d'investissement"), ('SUBV_EXPLOIT', "Subvention d'exploitation"), ('PARTENARIAT', 'Partenariat financier'), ('CROWDFUNDING', 'Financement participatif (crowdfunding)'), ('REVENU_EXCEPT', 'Revenu exceptionnel'), ('PRET', 'Prêt / crédit'), ('NATT', 'NATT / Tontine'), ('AUTRE', 'Autre source de financement')], default='DON', max_length=20)),
                ('nature_comptable', models.CharField(choices=[('PRODUIT', 'Produit'), ('CAPITAUX', 'Capitaux propres'), ('DETTE', 'Dette / financement')], default='PRODUIT', max_length=10)),
                ('compte_ressource', models.CharField(default='7588', max_length=10)),
                ('compte_tresorerie_defaut', models.CharField(default='571', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('est_actif', models.BooleanField(default=True)),
                ('est_systeme', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'gmrf_types_financement',
                'ordering': ['libelle'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='NattCotisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.IntegerField(help_text="Numéro d'échéance (1..durée)")),
                ('date_echeance', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('statut', models.CharField(choices=[('A_PAYER', 'À payer'), ('PAYE', 'Payée'), ('EN_RETARD', 'En retard')], default='A_PAYER', max_length=10)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('compte_tresorerie', models.CharField(blank=True, default='', max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='gmrf.nattcycle')),
            ],
            options={
                'db_table': 'gmrf_natt_cotisations',
                'ordering': ['cycle', 'numero'],
                'unique_together': {('tenant', 'cycle', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Financement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=30)),
                ('libelle', models.CharField(max_length=200)),
                ('source', models.CharField(blank=True, default='', max_length=150)),
                ('type_source', models.CharField(choices=[('ASSOCIATION', 'Association / ONG'), ('PARTICULIER', 'Particulier'), ('GROUPEMENT', 'Groupement / coopérative'), ('ENTREPRISE', 'Entreprise'), ('ETAT', 'État / collectivité'), ('AUTRE', 'Autre')], default='AUTRE', max_length=15)),
                ('coordonnees', models.TextField(blank=True, default='')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('devise', models.CharField(default='XOF', max_length=5)),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('compte_tresorerie', models.CharField(default='571', max_length=10)),
                ('compte_ressource', models.CharField(default='7588', max_length=10)),
                ('statut', models.CharField(choices=[('ATTENDU', 'Attendu / promis'), ('RECU', 'Reçu'), ('ANNULE', 'Annulé')], default='ATTENDU', max_length=10)),
                ('observations', models.TextField(blank=True, default='')),
                ('documents', models.JSONField(blank=True, default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('type_financement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financements', to='gmrf.typefinancement')),
            ],
            options={
                'db_table': 'gmrf_financements',
                'ordering': ['-date_reception', 'reference'],
                'unique_together': {('tenant', 'reference')},
            },
        ),
    ]
