# Generated by Django 5.1 on 2026-07-02 21:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmrf', '0001_initial'),
        ('tenants', '0006_tenant_nb_periodes_alter_tenant_periode_scolaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=30)),
                ('type_pret', models.CharField(choices=[('BANCAIRE', 'Prêt bancaire'), ('INSTITUTIONNEL', 'Prêt institutionnel'), ('MICROFINANCE', 'Prêt de microfinance'), ('GOUVERNEMENTAL', 'Prêt gouvernemental'), ('CREDIT_FOURNISSEUR', 'Crédit fournisseur'), ('AUTRE', 'Autre prêt')], default='BANCAIRE', max_length=20)),
                ('organisme_preteur', models.CharField(max_length=200)),
                ('objet', models.CharField(blank=True, default='', max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('devise', models.CharField(default='XOF', max_length=5)),
                ('taux_interet', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('duree_mois', models.IntegerField()),
                ('periodicite', models.CharField(choices=[('MENSUELLE', 'Mensuelle'), ('TRIMESTRIELLE', 'Trimestrielle'), ('SEMESTRIELLE', 'Semestrielle'), ('ANNUELLE', 'Annuelle')], default='MENSUELLE', max_length=15)),
                ('mode_amortissement', models.CharField(choices=[('CONSTANT', 'Échéances constantes (annuités constantes)'), ('CAPITAL_CONSTANT', 'Amortissement constant du capital'), ('IN_FINE', 'In fine (capital remboursé à la fin)')], default='CONSTANT', max_length=18)),
                ('date_deblocage', models.DateField()),
                ('date_premiere_echeance', models.DateField(blank=True, null=True)),
                ('frais_dossier', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('compte_tresorerie', models.CharField(default='521', max_length=10)),
                ('compte_emprunt', models.CharField(default='162', max_length=10)),
                ('compte_interets', models.CharField(default='671', max_length=10)),
                ('compte_frais', models.CharField(default='6312', max_length=10)),
                ('compte_penalites', models.CharField(default='6718', max_length=10)),
                ('garanties', models.TextField(blank=True, default='')),
                ('observations', models.TextField(blank=True, default='')),
                ('documents', models.JSONField(blank=True, default=list)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('SOLDE', 'Soldé'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'gmrf_prets',
                'ordering': ['-date_deblocage', 'reference'],
                'unique_together': {('tenant', 'reference')},
            },
        ),
        migrations.CreateModel(
            name='PretEcheance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.IntegerField()),
                ('date_echeance', models.DateField()),
                ('capital_debut', models.DecimalField(decimal_places=2, max_digits=15)),
                ('montant_echeance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('part_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('part_interet', models.DecimalField(decimal_places=2, max_digits=15)),
                ('capital_fin', models.DecimalField(decimal_places=2, max_digits=15)),
                ('penalite', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('statut', models.CharField(choices=[('A_PAYER', 'À payer'), ('PAYE', 'Payée'), ('EN_RETARD', 'En retard')], default='A_PAYER', max_length=10)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='gmrf.pret')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'gmrf_pret_echeances',
                'ordering': ['pret', 'numero'],
                'unique_together': {('tenant', 'pret', 'numero')},
            },
        ),
    ]
