# Generated by Django 5.1 on 2026-09-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmrf", "0002_pret_pretecheance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typefinancement",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("DON", "Don"),
                    ("SUBV_INVEST", "Subvention d'investissement"),
                    ("SUBV_EXPLOIT", "Subvention d'exploitation"),
                    ("PARTENARIAT", "Partenariat financier"),
                    ("CROWDFUNDING", "Financement participatif (crowdfunding)"),
                    ("REVENU_EXCEPT", "Revenu exceptionnel"),
                    ("PRET", "Prêt / crédit"),
                    ("NATT", "NATT / Tontine"),
                    ("APPORT", "Apport des fondateurs"),
                    ("AVANCE", "Avance d'associé / de fondateur"),
                    ("AUTRE", "Autre source de financement"),
                ],
                default="DON",
                max_length=20,
            ),
        ),
    ]
