# Generated by Django 5.1 on 2026-08-27 15:46

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0012_tenant_anciennete_renouvellement_mois"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prospect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("etablissement", models.CharField(max_length=200)),
                ("type_organisation", models.CharField(blank=True, max_length=30)),
                ("date_creation", models.CharField(blank=True, max_length=40)),
                ("adresse", models.CharField(blank=True, max_length=300)),
                ("ville", models.CharField(blank=True, max_length=120)),
                ("telephone", models.CharField(blank=True, max_length=60)),
                (
                    "telephone_cle",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("email", models.CharField(blank=True, max_length=254)),
                ("site_web", models.CharField(blank=True, max_length=200)),
                ("contact_nom", models.CharField(blank=True, max_length=200)),
                ("contact_fonction", models.CharField(blank=True, max_length=150)),
                ("contact_telephone", models.CharField(blank=True, max_length=60)),
                ("contact_email", models.CharField(blank=True, max_length=254)),
                ("pouvoir_decisionnel", models.CharField(blank=True, max_length=80)),
                ("origines", models.JSONField(blank=True, default=list)),
                ("origine_details", models.TextField(blank=True)),
                ("nb_eleves", models.PositiveIntegerField(blank=True, null=True)),
                ("nb_employes", models.PositiveIntegerField(blank=True, null=True)),
                ("nb_classes", models.PositiveIntegerField(blank=True, null=True)),
                ("nb_sites", models.PositiveIntegerField(blank=True, null=True)),
                ("disponibilites", models.CharField(blank=True, max_length=300)),
                ("message", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("NOUVEAU", "Nouveau — à rappeler"),
                            ("CONTACTE", "Contacté"),
                            ("QUALIFIE", "Qualifié — besoin identifié"),
                            ("DEVIS", "Devis envoyé"),
                            ("GAGNE", "Gagné — devenu client"),
                            ("PERDU", "Perdu"),
                        ],
                        db_index=True,
                        default="NOUVEAU",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SITE", "Formulaire du site"),
                            ("ASSISTANT", "Assistant SAMA"),
                            ("MANUEL", "Saisie manuelle"),
                            ("IMPORT", "Import"),
                        ],
                        default="SITE",
                        max_length=20,
                    ),
                ),
                ("relance_le", models.DateField(blank=True, db_index=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("perdu_motif", models.CharField(blank=True, max_length=250)),
                ("date_conversion", models.DateField(blank=True, null=True)),
                ("donnees_brutes", models.JSONField(blank=True, default=dict)),
                ("courriel_envoye", models.BooleanField(default=False)),
                (
                    "tenant_converti",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prospects",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prospect",
                "verbose_name_plural": "Prospects",
                "db_table": "prospects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InteractionProspect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("SITE", "Demande depuis le site"),
                            ("ASSISTANT", "Conversation avec SAMA"),
                            ("APPEL", "Appel téléphonique"),
                            ("WHATSAPP", "WhatsApp"),
                            ("EMAIL", "Courriel"),
                            ("VISITE", "Visite / rendez-vous"),
                            ("DEMO", "Démonstration"),
                            ("AUTRE", "Autre"),
                        ],
                        default="APPEL",
                        max_length=20,
                    ),
                ),
                ("resume", models.TextField()),
                ("auteur", models.CharField(blank=True, max_length=150)),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="prospects.prospect",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interaction",
                "verbose_name_plural": "Interactions",
                "db_table": "prospects_interactions",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="prospect",
            index=models.Index(
                fields=["statut", "-created_at"], name="prospects_statut_6f42f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prospect",
            index=models.Index(
                fields=["relance_le"], name="prospects_relance_cbe570_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interactionprospect",
            index=models.Index(
                fields=["prospect", "-date"], name="prospects_i_prospec_05eca8_idx"
            ),
        ),
    ]
