# Generated by Django 5.1 on 2026-08-27 17:15

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Devis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(max_length=30, unique=True)),
                ("etablissement", models.CharField(max_length=200)),
                ("ville", models.CharField(blank=True, max_length=120)),
                ("contact_nom", models.CharField(blank=True, max_length=200)),
                ("contact_fonction", models.CharField(blank=True, max_length=150)),
                ("telephone", models.CharField(blank=True, max_length=60)),
                ("email", models.CharField(blank=True, max_length=254)),
                ("type_licence", models.CharField(max_length=20)),
                ("cycle", models.CharField(default="ANNUEL", max_length=10)),
                ("mois", models.PositiveIntegerField(default=12)),
                (
                    "prix_mensuel",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "montant_brut",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "taux_remise",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "montant_remise",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "montant_net",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "frais_installation",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                ("prestations", models.TextField(blank=True)),
                (
                    "montant_prestations",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                ("observations", models.TextField(blank=True)),
                ("date_emission", models.DateField(default=datetime.date.today)),
                ("date_validite", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon — à valider"),
                            ("VALIDE", "Validé — prêt à envoyer"),
                            ("ENVOYE", "Envoyé au prospect"),
                            ("ACCEPTE", "Accepté"),
                            ("REFUSE", "Refusé"),
                        ],
                        db_index=True,
                        default="BROUILLON",
                        max_length=15,
                    ),
                ),
                ("etabli_par", models.CharField(blank=True, max_length=150)),
                ("valide_par", models.CharField(blank=True, max_length=150)),
                ("valide_le", models.DateTimeField(blank=True, null=True)),
                ("envoye_le", models.DateTimeField(blank=True, null=True)),
                (
                    "prospect",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devis",
                        to="prospects.prospect",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devis",
                "verbose_name_plural": "Devis",
                "db_table": "prospects_devis",
                "ordering": ["-date_emission", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["statut", "-date_emission"],
                        name="prospects_d_statut_f9a9d0_idx",
                    )
                ],
            },
        ),
    ]
