# Generated by Django 5.1 on 2026-09-16 21:54

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0002_devis"),
        ("tenants", "0013_programmes_hybrides"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParametresFacturation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "raison_sociale",
                    models.CharField(default="HADY GESMAN", max_length=200),
                ),
                ("forme_juridique", models.CharField(blank=True, max_length=100)),
                ("adresse", models.CharField(blank=True, max_length=300)),
                (
                    "ville",
                    models.CharField(blank=True, default="Dakar", max_length=120),
                ),
                ("telephone", models.CharField(blank=True, max_length=120)),
                ("email", models.CharField(blank=True, max_length=254)),
                ("site_web", models.CharField(blank=True, max_length=200)),
                ("ninea", models.CharField(blank=True, max_length=40)),
                ("rccm", models.CharField(blank=True, max_length=60)),
                ("tva_applicable", models.BooleanField(default=True)),
                (
                    "taux_tva",
                    models.DecimalField(decimal_places=2, default=18, max_digits=5),
                ),
                (
                    "mention_sans_tva",
                    models.CharField(
                        blank=True,
                        default="TVA non applicable — contribuable soumis à la Contribution globale unique (CGI, art. 134)",
                        max_length=250,
                    ),
                ),
                ("delai_paiement_jours", models.PositiveIntegerField(default=30)),
                ("validite_proforma_jours", models.PositiveIntegerField(default=30)),
                (
                    "coordonnees_paiement",
                    models.TextField(
                        blank=True,
                        help_text="Banque, IBAN, numéros Wave / Orange Money…",
                    ),
                ),
                ("conditions", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Paramètres de facturation",
                "db_table": "facturation_parametres",
            },
        ),
        migrations.CreateModel(
            name="DocumentCommercial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PROFORMA", "Facture proforma"),
                            ("FACTURE", "Facture"),
                            ("AVOIR", "Avoir"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("numero", models.CharField(blank=True, db_index=True, max_length=30)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("EMIS", "Émis"),
                            ("CONVERTI", "Converti en facture"),
                        ],
                        db_index=True,
                        default="BROUILLON",
                        max_length=10,
                    ),
                ),
                ("client_nom", models.CharField(max_length=200)),
                ("client_contact", models.CharField(blank=True, max_length=200)),
                ("client_adresse", models.CharField(blank=True, max_length=300)),
                ("client_ville", models.CharField(blank=True, max_length=120)),
                ("client_telephone", models.CharField(blank=True, max_length=60)),
                ("client_email", models.CharField(blank=True, max_length=254)),
                ("client_ninea", models.CharField(blank=True, max_length=40)),
                ("objet", models.CharField(blank=True, max_length=250)),
                ("date_emission", models.DateField(blank=True, null=True)),
                ("date_echeance", models.DateField(blank=True, null=True)),
                ("date_validite", models.DateField(blank=True, null=True)),
                ("tva_applicable", models.BooleanField(default=True)),
                (
                    "taux_tva",
                    models.DecimalField(decimal_places=2, default=18, max_digits=5),
                ),
                ("mention_tva", models.CharField(blank=True, max_length=250)),
                (
                    "total_ht",
                    models.DecimalField(decimal_places=0, default=0, max_digits=14),
                ),
                (
                    "montant_tva",
                    models.DecimalField(decimal_places=0, default=0, max_digits=14),
                ),
                (
                    "total_ttc",
                    models.DecimalField(decimal_places=0, default=0, max_digits=14),
                ),
                ("motif", models.TextField(blank=True)),
                ("conditions", models.TextField(blank=True)),
                ("observations", models.TextField(blank=True)),
                ("etabli_par", models.CharField(blank=True, max_length=150)),
                ("emis_par", models.CharField(blank=True, max_length=150)),
                ("emis_le", models.DateTimeField(blank=True, null=True)),
                (
                    "devis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="prospects.devis",
                    ),
                ),
                (
                    "origine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="derives",
                        to="prospects.documentcommercial",
                    ),
                ),
                (
                    "prospect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="prospects.prospect",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_commerciaux",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document commercial",
                "verbose_name_plural": "Documents commerciaux",
                "db_table": "facturation_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Encaissement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(max_length=30, unique=True)),
                ("date", models.DateField(default=datetime.date.today)),
                ("montant", models.DecimalField(decimal_places=0, max_digits=14)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("VIREMENT", "Virement bancaire"),
                            ("WAVE", "Wave"),
                            ("ORANGE_MONEY", "Orange Money"),
                            ("CHEQUE", "Chèque"),
                            ("ESPECES", "Espèces"),
                            ("AUTRE", "Autre"),
                        ],
                        default="VIREMENT",
                        max_length=15,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("observations", models.TextField(blank=True)),
                ("recu_par", models.CharField(blank=True, max_length=150)),
                ("annule", models.BooleanField(default=False)),
                ("annule_motif", models.CharField(blank=True, max_length=250)),
                ("annule_le", models.DateTimeField(blank=True, null=True)),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encaissements",
                        to="prospects.documentcommercial",
                    ),
                ),
            ],
            options={
                "db_table": "facturation_encaissements",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LigneDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("designation", models.CharField(max_length=250)),
                ("detail", models.TextField(blank=True)),
                (
                    "quantite",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("unite", models.CharField(blank=True, max_length=30)),
                (
                    "prix_unitaire",
                    models.DecimalField(decimal_places=0, default=0, max_digits=14),
                ),
                (
                    "montant",
                    models.DecimalField(decimal_places=0, default=0, max_digits=14),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="prospects.documentcommercial",
                    ),
                ),
            ],
            options={
                "db_table": "facturation_lignes",
                "ordering": ["ordre", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="documentcommercial",
            constraint=models.UniqueConstraint(
                condition=models.Q(("numero", ""), _negated=True),
                fields=("numero",),
                name="uniq_numero_document_commercial",
            ),
        ),
    ]
