# Generated by Django 5.1 on 2026-09-17 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0003_facturation"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentcommercial",
            name="montant_acompte",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="documentcommercial",
            name="prestation_demarree_le",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentcommercial",
            name="prestation_livree_le",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentcommercial",
            name="taux_acompte",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="parametresfacturation",
            name="taux_acompte_defaut",
            field=models.DecimalField(decimal_places=2, default=40, max_digits=5),
        ),
        migrations.CreateModel(
            name="JustificatifFacturation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type_piece",
                    models.CharField(
                        choices=[
                            ("PREUVE_PAIEMENT", "Preuve de paiement"),
                            ("BORDEREAU", "Avis de virement / bordereau"),
                            ("CHEQUE", "Chèque scanné"),
                            ("BON_COMMANDE", "Bon de commande signé"),
                            ("CONTRAT", "Contrat signé"),
                            ("PV_LIVRAISON", "Procès-verbal de livraison"),
                            ("AUTRE", "Autre pièce"),
                        ],
                        default="PREUVE_PAIEMENT",
                        max_length=20,
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("taille", models.PositiveIntegerField(default=0)),
                ("contenu", models.TextField()),
                ("observations", models.CharField(blank=True, max_length=250)),
                ("ajoute_par", models.CharField(blank=True, max_length=150)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="justificatifs",
                        to="prospects.documentcommercial",
                    ),
                ),
                (
                    "encaissement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="justificatifs",
                        to="prospects.encaissement",
                    ),
                ),
            ],
            options={
                "db_table": "facturation_justificatifs",
                "ordering": ["created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("document__isnull", False),
                            ("encaissement__isnull", False),
                            _connector="OR",
                        ),
                        name="justificatif_rattache",
                    )
                ],
            },
        ),
    ]
