# Generated by Django 5.1 on 2026-03-27 23:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cle_licence', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('ESSAI', 'Essai 30 jours'), ('BASIC', 'Basic'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='ESSAI', max_length=20)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIREE', 'Expirée'), ('SUSPENDUE', 'Suspendue'), ('ESSAI', 'Essai')], default='ESSAI', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('version', models.CharField(default='2.2.0', max_length=20)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='licence', to='tenants.tenant')),
            ],
            options={
                'db_table': 'licences',
            },
        ),
    ]
