# Generated by Django 5.1 on 2026-09-13 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licences", "0002_alter_licence_type"),
        ("tenants", "0012_tenant_anciennete_renouvellement_mois"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeRenouvellement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ecole_nom", models.CharField(max_length=200)),
                (
                    "cle_licence",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "type_licence",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("demandeur", models.CharField(blank=True, default="", max_length=200)),
                (
                    "email_demandeur",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                ("telephone", models.CharField(blank=True, default="", max_length=40)),
                ("message", models.TextField(blank=True, default="")),
                (
                    "origine",
                    models.CharField(
                        choices=[
                            ("CLOUD", "Application cloud"),
                            ("RELAIS", "Installation locale (relayée au cloud)"),
                            ("LOCAL", "Installation locale (non relayée)"),
                        ],
                        default="CLOUD",
                        max_length=10,
                    ),
                ),
                ("courriel_envoye", models.BooleanField(default=False)),
                ("relayee", models.BooleanField(default=False)),
                ("erreur", models.TextField(blank=True, default="")),
                ("traitee", models.BooleanField(default=False)),
                ("traitee_le", models.DateTimeField(blank=True, null=True)),
                (
                    "licence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_renouvellement",
                        to="licences.licence",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_renouvellement",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "demandes_renouvellement",
                "ordering": ["-created_at"],
            },
        ),
    ]
