# Generated by Django 5.1 on 2026-09-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licences", "0003_demandes_renouvellement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demanderenouvellement",
            name="telephone",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
    ]
