# Generated by Django 5.1 on 2026-10-05 00:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0020_tenant_agregation_domaines_tenant_format_bulletin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObligationFiscale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("libelle", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "base",
                    models.CharField(
                        choices=[
                            ("RESULTAT", "Résultat fiscal estimé"),
                            ("PRODUITS", "Chiffre d'affaires / produits"),
                            ("TVA_NETTE", "TVA collectée − TVA déductible"),
                            ("MASSE_SALARIALE", "Masse salariale brute"),
                            ("SAISIE", "Montant de l'avis (saisi)"),
                            ("AUCUNE", "Information"),
                        ],
                        default="AUCUNE",
                        max_length=20,
                    ),
                ),
                (
                    "formule",
                    models.CharField(
                        choices=[
                            ("TAUX", "Base × taux"),
                            (
                                "IS_IMF",
                                "Plus élevé de IS (taux × résultat) et IMF (minimum forfaitaire)",
                            ),
                            (
                                "MASSE_SALARIALE",
                                "Masse salariale × taux (bulletins de paie si disponibles)",
                            ),
                            ("TVA", "TVA nette du journal"),
                            ("SAISIE", "Montant saisi"),
                            ("RH", "Calculée par le module RH"),
                            ("INFO", "Information seulement"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("parametres", models.JSONField(blank=True, default=dict)),
                (
                    "periodicite",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("echeance", models.CharField(blank=True, default="", max_length=250)),
                (
                    "compte_debit",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "compte_credit",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("message_non_applicable", models.TextField(blank=True, default="")),
                ("reference", models.CharField(blank=True, default="", max_length=250)),
                ("a_verifier", models.BooleanField(default=False)),
                ("ordre", models.IntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "fiscal_obligations",
                "ordering": ["ordre", "code"],
            },
        ),
        migrations.CreateModel(
            name="ProfilFiscal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "forme_juridique",
                    models.CharField(
                        choices=[
                            ("SA", "Société anonyme (SA)"),
                            ("SARL", "SARL"),
                            ("SUARL", "SUARL"),
                            ("SAS", "SAS"),
                            ("SNC", "Société en nom collectif"),
                            ("EI", "Entreprise individuelle"),
                            ("GIE", "Groupement d'intérêt économique"),
                            ("ASSOCIATION", "Association"),
                            ("FONDATION", "Fondation"),
                            ("ONG", "ONG"),
                            ("CONGREGATION", "Congrégation / institution religieuse"),
                            ("COOPERATIVE", "Coopérative"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=15,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PRIVE_LAIC", "Privé laïc"),
                            ("PRIVE_CATHOLIQUE", "Privé catholique"),
                            ("FRANCO_ARABE", "Franco-arabe"),
                            ("DAARA", "Daara (école coranique)"),
                            ("COMMUNAUTAIRE", "Communautaire / associatif"),
                            ("FORMATION_PRO", "Formation professionnelle"),
                            ("SUPERIEUR", "Enseignement supérieur privé"),
                            ("AUTRE", "Autre"),
                        ],
                        default="PRIVE_LAIC",
                        max_length=20,
                    ),
                ),
                ("but_lucratif", models.BooleanField(default=True)),
                (
                    "regime",
                    models.CharField(
                        choices=[
                            ("REEL_NORMAL", "Régime du réel normal"),
                            ("REEL_SIMPLIFIE", "Régime du réel simplifié"),
                            ("CGU", "Contribution globale unique (CGU)"),
                            ("NON_ASSUJETTI", "Non assujetti (exonéré total)"),
                        ],
                        default="REEL_NORMAL",
                        max_length=15,
                    ),
                ),
                ("assujetti_tva", models.BooleanField(default=False)),
                ("proprietaire_locaux", models.BooleanField(default=False)),
                (
                    "centre_fiscal",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("date_debut_activite", models.DateField(blank=True, null=True)),
                (
                    "numero_agrement",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("exonerations", models.JSONField(blank=True, default=list)),
                ("observations", models.TextField(blank=True, default="")),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil_fiscal",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "fiscal_profils",
            },
        ),
        migrations.CreateModel(
            name="ParametreFiscal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=40)),
                ("libelle", models.CharField(max_length=200)),
                ("valeur", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "unite",
                    models.CharField(
                        choices=[
                            ("%", "Pourcentage"),
                            ("FCFA", "Montant en FCFA"),
                            ("MOIS", "Mois"),
                            ("JOUR", "Jour du mois"),
                            ("NOMBRE", "Nombre"),
                        ],
                        default="%",
                        max_length=6,
                    ),
                ),
                ("date_effet", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, default="", max_length=250)),
                ("a_verifier", models.BooleanField(default=False)),
                ("observations", models.TextField(blank=True, default="")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parametres_fiscaux",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "fiscal_parametres",
                "ordering": ["code", "-date_effet"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "code", "date_effet"),
                        name="uniq_param_fiscal_date",
                    )
                ],
            },
        ),
    ]
