# Generated by Django 5.1 on 2026-06-27 23:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0010_eleve_classe'),
        ('tenants', '0006_tenant_nb_periodes_alter_tenant_periode_scolaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sourate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('nom_ar', models.CharField(max_length=100)),
                ('nom_fr', models.CharField(max_length=100)),
                ('type_revelation', models.CharField(choices=[('MECQUOISE', 'Mecquoise'), ('MEDINOISE', 'Médinoise')], max_length=10)),
                ('nb_versets_hafs', models.PositiveSmallIntegerField()),
                ('nb_versets_warsh', models.PositiveSmallIntegerField()),
                ('ordre_revelation', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coran_sourates',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='NiveauDaara',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_fr', models.CharField(max_length=100)),
                ('nom_ar', models.CharField(blank=True, max_length=100)),
                ('categorie', models.CharField(choices=[('IDJIE', 'Idjie (alphabet arabe)'), ('MEMORISATION', 'Mémorisation'), ('AUTRE', 'Autre')], default='MEMORISATION', max_length=15)),
                ('ordre', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'daara_niveaux',
                'ordering': ['ordre', 'nom_fr'],
            },
        ),
        migrations.CreateModel(
            name='ParcoursNongo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('riwaya', models.CharField(choices=[('HAFS', 'Hafs'), ('WARSH', 'Warsh')], default='WARSH', max_length=6)),
                ('sens', models.CharField(choices=[('FIN', 'Depuis la fin (An-Nas → Al-Baqara)'), ('DEBUT', 'Depuis le début (Al-Baqara → An-Nas)')], default='FIN', max_length=5)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('SORTI', 'Sorti'), ('KHATMA', 'Khatma (Coran terminé)')], default='EN_COURS', max_length=10)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours_coranique', to='eleves.eleve')),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcours', to='daara.niveaudaara')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'daara_parcours',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'eleve')},
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riwaya', models.CharField(choices=[('HAFS', 'Hafs'), ('WARSH', 'Warsh')], max_length=6)),
                ('type', models.CharField(choices=[('JUZ', 'Juz'), ('HIZB', 'Hizb'), ('NISF', 'Nisf'), ('RUB', "Rub'")], max_length=5)),
                ('numero', models.PositiveSmallIntegerField()),
                ('verset_debut', models.PositiveSmallIntegerField(default=1)),
                ('sourate_debut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='daara.sourate')),
            ],
            options={
                'db_table': 'coran_subdivisions',
                'ordering': ['riwaya', 'type', 'numero'],
                'unique_together': {('riwaya', 'type', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='SuiviQuotidien',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('verset_debut', models.PositiveSmallIntegerField(default=1)),
                ('verset_fin', models.PositiveSmallIntegerField(default=1)),
                ('qualite', models.CharField(choices=[('BIEN', 'Bien'), ('MOYEN', 'Moyen'), ('A_REVOIR', 'À revoir')], default='MOYEN', max_length=10)),
                ('present', models.BooleanField(default=True)),
                ('observation', models.TextField(blank=True)),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='daara.parcoursnongo')),
                ('sourate_debut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='daara.sourate')),
                ('sourate_fin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='daara.sourate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'daara_suivi_quotidien',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['parcours', 'date'], name='daara_suivi_parcour_9267f0_idx')],
            },
        ),
    ]
