# Generated by Django 5.2.13 on 2026-06-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daara', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcoursnongo',
            name='niveau_idjie',
            field=models.CharField(blank=True, choices=[('DEBUTANT', 'Débutant'), ('MOYEN', 'Moyen'), ('AVANCE', 'Avancé')], max_length=10, null=True),
        ),
    ]
