# Generated by Django 5.1 on 2026-07-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daara", "0002_parcoursnongo_niveau_idjie"),
    ]

    operations = [
        migrations.AddField(
            model_name="suiviquotidien",
            name="hizb_debut",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suiviquotidien",
            name="hizb_fin",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suiviquotidien",
            name="mode",
            field=models.CharField(
                choices=[("SOURATE", "Par sourate"), ("HIZB", "Par hizb")],
                default="SOURATE",
                max_length=8,
            ),
        ),
    ]
