# Generated by Django 5.1 on 2026-07-22 22:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0008_tenant_config_certificat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PieceJustificative",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "objet_type",
                    models.CharField(
                        choices=[
                            ("CHARGE", "Charge / dépense"),
                            ("PAIEMENT", "Paiement / recette"),
                            ("IMMOBILISATION", "Immobilisation"),
                            ("FINANCEMENT", "Financement (GMRF)"),
                            ("PRET", "Prêt"),
                            ("NATT", "NATT / Tontine"),
                            ("PROJET", "Projet"),
                            ("ECRITURE", "Écriture comptable"),
                            ("RESSOURCE", "Ressource financière"),
                            ("TRANSFERT", "Transfert de trésorerie"),
                            ("PROVISION", "Provision"),
                            ("RAPPROCHEMENT", "Rapprochement bancaire"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("objet_id", models.UUIDField()),
                (
                    "type_piece",
                    models.CharField(
                        choices=[
                            ("FACTURE", "Facture"),
                            ("DEVIS", "Devis"),
                            ("BON_COMMANDE", "Bon de commande"),
                            ("BON_LIVRAISON", "Bon de livraison"),
                            ("CONTRAT", "Contrat"),
                            ("CONVENTION", "Convention"),
                            ("RECU", "Reçu"),
                            ("RELEVE", "Relevé bancaire"),
                            ("PHOTO", "Photo"),
                            ("PDF", "Document PDF"),
                            ("WORD", "Document Word"),
                            ("AUTRE", "Autre document"),
                        ],
                        default="AUTRE",
                        max_length=15,
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("mime_type", models.CharField(blank=True, default="", max_length=100)),
                ("taille", models.IntegerField(default=0)),
                ("contenu", models.TextField()),
                ("reference", models.CharField(blank=True, default="", max_length=80)),
                ("date_document", models.DateField(blank=True, null=True)),
                ("observations", models.TextField(blank=True, default="")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "uploaded_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gouvernance_pieces",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "objet_type", "objet_id"],
                        name="idx_piece_objet",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30)),
                ("libelle", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "responsable",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("date_debut", models.DateField(blank=True, null=True)),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "budget_prevu",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PLANIFIE", "Planifié"),
                            ("EN_COURS", "En cours"),
                            ("SUSPENDU", "Suspendu"),
                            ("TERMINE", "Terminé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="PLANIFIE",
                        max_length=10,
                    ),
                ),
                ("observations", models.TextField(blank=True, default="")),
                ("est_actif", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "gouvernance_projets",
                "ordering": ["-date_debut", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "code"), name="uniq_projet_code_par_tenant"
                    )
                ],
            },
        ),
    ]
