# Generated by Django 5.1 on 2026-07-22 23:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gouvernance", "0001_initial"),
        ("paiements", "0008_alter_paiement_mode_paiement"),
        ("tenants", "0008_tenant_config_certificat"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransfertTresorerie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=30)),
                ("date_transfert", models.DateField()),
                ("compte_source", models.CharField(max_length=10)),
                ("compte_destination", models.CharField(max_length=10)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "frais",
                    models.DecimalField(decimal_places=2, default=0, max_digits=13),
                ),
                ("compte_virement", models.CharField(default="585", max_length=10)),
                ("compte_frais", models.CharField(default="6312", max_length=10)),
                ("motif", models.CharField(blank=True, default="", max_length=200)),
                (
                    "statut",
                    models.CharField(
                        choices=[("ACTIF", "Actif"), ("ANNULE", "Annulé")],
                        default="ACTIF",
                        max_length=10,
                    ),
                ),
                ("observations", models.TextField(blank=True, default="")),
                (
                    "exercice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transferts",
                        to="paiements.exercice",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferts",
                        to="gouvernance.projet",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "gouvernance_transferts",
                "ordering": ["-date_transfert", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "reference"),
                        name="uniq_transfert_ref_par_tenant",
                    )
                ],
            },
        ),
    ]
