# Generated by Django 5.1 on 2026-07-22 23:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmrf", "0002_pret_pretecheance"),
        ("gouvernance", "0002_transferttresorerie"),
        ("tenants", "0008_tenant_config_certificat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ressource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=30)),
                (
                    "type_ressource",
                    models.CharField(
                        choices=[
                            ("FONDS_PROPRES", "Fonds propres"),
                            ("PRET", "Prêt"),
                            ("SUBVENTION", "Subvention"),
                            ("DON", "Don"),
                            ("PARTENAIRE", "Partenaire"),
                            ("PROJET", "Financement de projet"),
                            ("COTISATION_EXCEPT", "Cotisation exceptionnelle"),
                            ("AVANCE_TRESO", "Avance de trésorerie"),
                            ("RECETTES_SCOLAIRES", "Recettes scolaires"),
                            ("AUTRE", "Autre ressource"),
                        ],
                        default="AUTRE",
                        max_length=20,
                    ),
                ),
                ("libelle", models.CharField(max_length=200)),
                ("organisme", models.CharField(blank=True, default="", max_length=200)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=15)),
                ("date_ressource", models.DateField(blank=True, null=True)),
                (
                    "compte_tresorerie",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "convention",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "taux",
                    models.DecimalField(decimal_places=3, default=0, max_digits=6),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CLOTUREE", "Clôturée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("observations", models.TextField(blank=True, default="")),
                (
                    "financement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ressources_gouv",
                        to="gmrf.financement",
                    ),
                ),
                (
                    "pret",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ressources_gouv",
                        to="gmrf.pret",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ressources",
                        to="gouvernance.projet",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "gouvernance_ressources",
                "ordering": ["-date_ressource", "reference"],
            },
        ),
        migrations.CreateModel(
            name="AffectationRessource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type_emploi",
                    models.CharField(
                        choices=[
                            ("IMMOBILISATION", "Immobilisation"),
                            ("EQUIPEMENT", "Équipement"),
                            ("TRAVAUX", "Travaux"),
                            ("MOBILIER", "Mobilier"),
                            ("FONCTIONNEMENT", "Fonctionnement"),
                            ("SALAIRES", "Salaires"),
                            ("PROJET", "Projet"),
                            ("TRESORERIE", "Trésorerie"),
                            ("AUTRE", "Autre emploi"),
                        ],
                        default="AUTRE",
                        max_length=15,
                    ),
                ),
                ("libelle", models.CharField(max_length=200)),
                (
                    "montant_affecte",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("date_affectation", models.DateField(blank=True, null=True)),
                ("observations", models.TextField(blank=True, default="")),
                (
                    "projet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affectations",
                        to="gouvernance.projet",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "ressource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affectations",
                        to="gouvernance.ressource",
                    ),
                ),
            ],
            options={
                "db_table": "gouvernance_affectations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="ressource",
            constraint=models.UniqueConstraint(
                fields=("tenant", "reference"), name="uniq_ressource_ref_par_tenant"
            ),
        ),
    ]
