# Generated by Django 5.1 on 2026-07-23 00:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gouvernance", "0003_ressource_affectationressource_and_more"),
        ("paiements", "0008_alter_paiement_mode_paiement"),
        ("tenants", "0008_tenant_config_certificat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=30)),
                (
                    "type_provision",
                    models.CharField(
                        choices=[
                            ("RISQUE", "Provision pour risques"),
                            ("LITIGE", "Provision pour litiges"),
                            ("CHARGE", "Provision pour charges"),
                            ("CREANCE_DOUTEUSE", "Dépréciation de créances douteuses"),
                            ("REGLEMENTEE", "Provision réglementée"),
                        ],
                        default="RISQUE",
                        max_length=20,
                    ),
                ),
                ("libelle", models.CharField(max_length=200)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "montant_repris",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("date_dotation", models.DateField()),
                ("compte_dotation", models.CharField(default="6911", max_length=10)),
                ("compte_provision", models.CharField(default="191", max_length=10)),
                ("compte_reprise", models.CharField(default="7911", max_length=10)),
                ("tiers", models.CharField(blank=True, default="", max_length=200)),
                ("observations", models.TextField(blank=True, default="")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SOLDEE", "Soldée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "exercice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provisions",
                        to="paiements.exercice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "gouvernance_provisions",
                "ordering": ["-date_dotation", "reference"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "reference"),
                        name="uniq_provision_ref_par_tenant",
                    )
                ],
            },
        ),
    ]
