# Generated by Django 5.1 on 2026-07-23 00:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0011_immobilisation_projet_immobilisation_ressource"),
        ("gouvernance", "0004_provision"),
        ("paiements", "0008_alter_paiement_mode_paiement"),
        ("tenants", "0008_tenant_config_certificat"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompteBancaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("libelle", models.CharField(max_length=150)),
                ("banque", models.CharField(blank=True, default="", max_length=150)),
                (
                    "numero_compte",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("no_compte_comptable", models.CharField(default="521", max_length=10)),
                ("devise", models.CharField(default="XOF", max_length=5)),
                (
                    "solde_initial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "gouvernance_comptes_bancaires",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="Rapprochement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=30)),
                ("date_rapprochement", models.DateField()),
                (
                    "solde_releve",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("EN_COURS", "En cours"), ("VALIDE", "Validé")],
                        default="EN_COURS",
                        max_length=10,
                    ),
                ),
                ("observations", models.TextField(blank=True, default="")),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                (
                    "compte_bancaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapprochements",
                        to="gouvernance.comptebancaire",
                    ),
                ),
                (
                    "exercice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapprochements",
                        to="paiements.exercice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "gouvernance_rapprochements",
                "ordering": ["-date_rapprochement"],
            },
        ),
        migrations.CreateModel(
            name="LigneReleve",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_operation", models.DateField()),
                ("libelle", models.CharField(max_length=200)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "sens",
                    models.CharField(
                        choices=[
                            ("ENTREE", "Entrée (encaissement)"),
                            ("SORTIE", "Sortie (décaissement)"),
                        ],
                        max_length=6,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=80)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("NON_RAPPROCHEE", "Non rapprochée"),
                            ("RAPPROCHEE", "Rapprochée"),
                            ("REGULARISEE", "Régularisée"),
                        ],
                        default="NON_RAPPROCHEE",
                        max_length=15,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="comptabilite.journalentry",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "rapprochement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="gouvernance.rapprochement",
                    ),
                ),
            ],
            options={
                "db_table": "gouvernance_lignes_releve",
                "ordering": ["date_operation", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="rapprochement",
            constraint=models.UniqueConstraint(
                fields=("tenant", "reference"), name="uniq_rapprochement_ref_par_tenant"
            ),
        ),
    ]
