# Generated by Django 5.1 on 2026-07-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gouvernance", "0005_comptebancaire_rapprochement_lignereleve_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="piecejustificative",
            name="objet_type",
            field=models.CharField(
                choices=[
                    ("CHARGE", "Charge / dépense"),
                    ("PAIEMENT", "Paiement / recette"),
                    ("IMMOBILISATION", "Immobilisation"),
                    ("BUDGET", "Ligne de budget"),
                    ("FINANCEMENT", "Financement (GMRF)"),
                    ("PRET", "Prêt"),
                    ("NATT", "NATT / Tontine"),
                    ("PROJET", "Projet"),
                    ("ECRITURE", "Écriture comptable"),
                    ("RESSOURCE", "Ressource financière"),
                    ("TRANSFERT", "Transfert de trésorerie"),
                    ("PROVISION", "Provision"),
                    ("RAPPROCHEMENT", "Rapprochement bancaire"),
                    ("AUTRE", "Autre"),
                ],
                max_length=20,
            ),
        ),
    ]
