# Generated by Django 5.1 on 2026-09-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmrf", "0003_categories_apport_avance"),
        ("gouvernance", "0006_alter_piecejustificative_objet_type"),
        ("tenants", "0019_tutelle_academique"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ressource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("financement__isnull", False)),
                fields=("financement",),
                name="uniq_ressource_par_financement",
            ),
        ),
        migrations.AddConstraint(
            model_name="ressource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pret__isnull", False)),
                fields=("pret",),
                name="uniq_ressource_par_pret",
            ),
        ),
    ]
