# Generated by Django 5.1 on 2026-10-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gouvernance", "0007_ressource_unique_par_operation_gmrf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="piecejustificative",
            name="objet_type",
            field=models.CharField(
                choices=[
                    ("CHARGE", "Charge / dépense"),
                    ("PAIEMENT", "Paiement / recette"),
                    ("IMMOBILISATION", "Immobilisation"),
                    ("BUDGET", "Ligne de budget"),
                    ("FINANCEMENT", "Financement (GMRF)"),
                    ("PRET", "Prêt"),
                    ("NATT", "NATT / Tontine"),
                    ("PROJET", "Projet"),
                    ("ECRITURE", "Écriture comptable"),
                    ("RESSOURCE", "Ressource financière"),
                    ("TRANSFERT", "Transfert de trésorerie"),
                    ("PROVISION", "Provision"),
                    ("RAPPROCHEMENT", "Rapprochement bancaire"),
                    ("FACTURE_ACT", "Facture d'activité"),
                    ("REGLEMENT_ACT", "Règlement de facture d'activité"),
                    ("FISCAL", "Déclaration / paiement fiscal"),
                    ("EXERCICE", "Exercice comptable (ETAFI, balance, PV)"),
                    ("AUTRE", "Autre"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="piecejustificative",
            name="type_piece",
            field=models.CharField(
                choices=[
                    ("FACTURE", "Facture"),
                    ("DEVIS", "Devis"),
                    ("BON_COMMANDE", "Bon de commande"),
                    ("BON_LIVRAISON", "Bon de livraison"),
                    ("CONTRAT", "Contrat"),
                    ("CONVENTION", "Convention"),
                    ("RECU", "Reçu"),
                    ("RELEVE", "Relevé bancaire"),
                    ("CHEQUE", "Chèque (copie)"),
                    ("BORDEREAU", "Bordereau de versement / remise"),
                    ("AVIS_IMPOT", "Avis d'imposition"),
                    ("DECLARATION", "Déclaration fiscale / sociale"),
                    ("QUITTANCE", "Quittance de paiement"),
                    ("ETAT_FIN", "États financiers / liasse"),
                    ("PV", "Procès-verbal (AG, conseil)"),
                    ("PHOTO", "Photo"),
                    ("PDF", "Document PDF"),
                    ("WORD", "Document Word"),
                    ("AUTRE", "Autre document"),
                ],
                default="AUTRE",
                max_length=15,
            ),
        ),
    ]
