# Generated by Django 5.1 on 2026-03-27 23:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('nom_complet', models.CharField(max_length=200)),
                ('genre', models.CharField(blank=True, choices=[('G', 'Garçon'), ('F', 'Fille')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('telephone_parent', models.CharField(blank=True, max_length=20)),
                ('nom_parent', models.CharField(blank=True, max_length=200)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('INSCRIT', 'Inscrit'), ('TRANSFERE', 'Transféré'), ('ABANDONNE', 'Abandonné'), ('DIPLOME', 'Diplômé')], default='INSCRIT', max_length=20)),
            ],
            options={
                'db_table': 'eleves',
                'ordering': ['numero', 'nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('frais_inscription', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frais_mensualite', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frais_uniforme', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frais_fournitures', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frais_yendu', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sections',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
