# Generated by Django 5.1 on 2026-05-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
