# Generated by Django 5.1 on 2026-05-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0004_eleve_parents_lieu_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='obs_prise_en_charge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='prise_en_charge',
            field=models.CharField(blank=True, choices=[('ORPHELIN', 'Orphelin'), ('HANDICAP', 'Handicap'), ('FAMILLE_DEMUNIE', 'Famille démunie'), ('AUTRE', 'Autre')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='taux_prise_en_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% de réduction appliquée', max_digits=5),
        ),
    ]
