# Generated by Django 5.1 on 2026-06-19 00:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0006_prise_en_charge_type_taux'),
        ('tenants', '0002_tenant_code_etablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='taux_prise_en_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('periodicite', models.CharField(choices=[('UNIQUE', 'Paiement unique'), ('MENSUEL', 'Mensuel')], default='MENSUEL', max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'services',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='EleveService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='eleves.eleve')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='eleves.service')),
            ],
            options={
                'db_table': 'eleve_services',
                'unique_together': {('tenant', 'eleve', 'service')},
            },
        ),
    ]
