# Generated by Django 5.1 on 2026-06-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0007_alter_eleve_taux_prise_en_charge_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='frais_yendu',
        ),
    ]
