# Generated by Django 5.1 on 2026-06-19 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0008_remove_section_frais_yendu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='date_inscription',
            field=models.DateField(default=datetime.date.today, help_text="Date d'entrée — sert au prorata des mensualités dues"),
        ),
    ]
