# Generated by Django 5.1 on 2026-06-20 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0002_alter_classe_code_alter_classe_niveau'),
        ('eleves', '0009_alter_eleve_date_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves_classe', to='academique.classe'),
        ),
    ]
