# Generated by Django 5.2.13 on 2026-06-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0003_alter_evaluation_trimestre'),
        ('eleves', '0010_eleve_classe'),
        ('paiements', '0007_alter_paiement_no_piece_and_more'),
        ('tenants', '0006_tenant_nb_periodes_alter_tenant_periode_scolaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='eleve',
            constraint=models.UniqueConstraint(fields=('tenant', 'matricule'), name='uniq_matricule_par_tenant'),
        ),
    ]
