# Generated by Django 5.1 on 2026-07-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0011_alter_eleve_matricule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleve",
            name="nb_mois_passager",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Mensualités dues depuis la date d'entrée (régime passager)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eleve",
            name="regime",
            field=models.CharField(
                choices=[
                    ("EXERCICE", "Permanent — mensualités de l'exercice"),
                    ("PASSAGER", "Passager — durée convenue en mois"),
                ],
                default="EXERCICE",
                max_length=10,
            ),
        ),
    ]
