# Generated by Django 5.1 on 2026-07-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0015_fold_uniforme_fournitures_composition"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleve",
            name="etat_sante",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SAIN", "Sain"),
                    ("SUIVI", "Sous suivi médical"),
                    ("CHRONIQUE", "Maladie chronique"),
                ],
                default="SAIN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="eleve",
            name="lien_tuteur",
            field=models.CharField(
                blank=True,
                help_text="Lien avec l'élève (oncle, grand-père, tuteur légal…)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="eleve",
            name="nom_tuteur",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="eleve",
            name="observations_sante",
            field=models.TextField(
                blank=True,
                help_text="Allergies, maladies chroniques, traitements en cours…",
            ),
        ),
        migrations.AddField(
            model_name="eleve",
            name="telephone_tuteur",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
