# Generated by Django 5.1 on 2026-07-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0016_eleve_etat_sante_eleve_lien_tuteur_eleve_nom_tuteur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleve",
            name="date_inscription_jour_estime",
            field=models.BooleanField(default=False),
        ),
    ]
