# Generated by Django 5.1 on 2026-07-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0017_eleve_date_inscription_jour_estime"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleve",
            name="pec_inscription",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Montant pris en charge sur l'inscription (FCFA)",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="eleve",
            name="pec_mensualite",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Montant pris en charge par mois (FCFA)",
                max_digits=12,
            ),
        ),
    ]
