# Generated by Django 5.1 on 2026-07-25 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academique", "0003_alter_evaluation_trimestre"),
        ("eleves", "0019_pec_taux_vers_montant"),
        ("paiements", "0010_paiement_montant_reliquat"),
        ("tenants", "0008_tenant_config_certificat"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="eleve",
            name="uniq_matricule_par_tenant",
        ),
        migrations.AddField(
            model_name="eleve",
            name="eleve_precedent",
            field=models.ForeignKey(
                blank=True,
                help_text="Fiche du même élève sur l'exercice précédent",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reinscriptions",
                to="eleves.eleve",
            ),
        ),
        migrations.AddField(
            model_name="eleve",
            name="reliquat_anterieur",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Reste dû reporté de l'exercice précédent (FCFA)",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="eleve",
            name="reliquat_exercice_origine",
            field=models.ForeignKey(
                blank=True,
                help_text="Exercice d'où provient le reliquat",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reliquats_reportes",
                to="paiements.exercice",
            ),
        ),
        migrations.AddConstraint(
            model_name="eleve",
            constraint=models.UniqueConstraint(
                fields=("tenant", "exercice", "matricule"),
                name="uniq_matricule_par_exercice",
            ),
        ),
    ]
