# Generated by Django 5.1 on 2026-07-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0020_remove_eleve_uniq_matricule_par_tenant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleve",
            name="reliquat_note",
            field=models.CharField(
                blank=True,
                help_text="Origine de l'impayé antérieur saisi à la migration",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="eleve",
            name="reliquat_anterieur",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Reste dû des années antérieures (FCFA)",
                max_digits=12,
            ),
        ),
    ]
