# Generated by Django 5.1 on 2026-07-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0021_eleve_reliquat_note_alter_eleve_reliquat_anterieur"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleve",
            name="annee_entree",
            field=models.CharField(
                blank=True,
                help_text="Année scolaire d'entrée (promo), ex. 2025-2026",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="eleve",
            name="date_entree",
            field=models.DateField(
                blank=True,
                help_text="Date de première entrée dans l'établissement",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eleve",
            name="matricule_ancien",
            field=models.CharField(
                blank=True, help_text="Matricule d'avant le rebasage", max_length=20
            ),
        ),
    ]
