# Generated by Django 5.1 on 2026-07-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0022_eleve_annee_entree_eleve_date_entree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleve",
            name="fiche_creance",
            field=models.BooleanField(
                default=False,
                help_text="Fiche de suivi de créance — l'élève a quitté l'établissement",
            ),
        ),
    ]
