# Generated by Django 5.1 on 2026-07-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0024_eleve_mois_dus_pec_montants_seule_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleve",
            name="date_sortie",
            field=models.DateField(
                blank=True, help_text="Date de sortie de l'établissement", null=True
            ),
        ),
    ]
