# Generated by Django 5.1 on 2026-07-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0025_eleve_date_sortie"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleve",
            name="imputation_mois",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Répartition manuelle du payé par mois",
            ),
        ),
    ]
