# Generated by Django 5.1 on 2026-07-28 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0026_eleve_imputation_mois"),
        ("tenants", "0010_tenant_rappel_message_tenant_sms_actif_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RappelEnvoye",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("periode", models.CharField(max_length=7)),
                ("canal", models.CharField(default="SMS", max_length=10)),
                ("destinataire", models.CharField(max_length=40)),
                ("message", models.TextField()),
                (
                    "montant",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ENVOYE", "Envoyé"),
                            ("ECHEC", "Échec"),
                            ("SIMULE", "Simulé (aucun envoi réel)"),
                        ],
                        default="ENVOYE",
                        max_length=10,
                    ),
                ),
                (
                    "detail",
                    models.TextField(blank=True, help_text="Réponse du fournisseur"),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rappels",
                        to="eleves.eleve",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "rappels_envoyes",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "eleve", "periode"),
                        name="uniq_rappel_par_mois",
                    )
                ],
            },
        ),
    ]
