# Generated by Django 5.1 on 2026-07-28 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0027_rappelenvoye"),
        ("paiements", "0010_paiement_montant_reliquat"),
        ("tenants", "0010_tenant_rappel_message_tenant_sms_actif_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ETAT", "État / Ministère"),
                            ("COLLECTIVITE", "Collectivité territoriale"),
                            ("ONG", "ONG"),
                            ("FONDATION", "Fondation"),
                            ("ENTREPRISE", "Entreprise"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Convention, arrêté, marché…",
                        max_length=100,
                    ),
                ),
                ("contact_nom", models.CharField(blank=True, max_length=150)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("adresse", models.TextField(blank=True)),
                ("observations", models.TextField(blank=True)),
                ("actif", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "organismes",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="PriseEnChargeOrganisme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "montant_inscription",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "montant_mensualite",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Par mensualité",
                        max_digits=12,
                    ),
                ),
                ("couvre_services", models.BooleanField(default=False)),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de bourse, décision d'attribution…",
                        max_length=100,
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prises_en_charge_organisme",
                        to="eleves.eleve",
                    ),
                ),
                (
                    "exercice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prises_en_charge_organisme",
                        to="paiements.exercice",
                    ),
                ),
                (
                    "organisme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prises_en_charge",
                        to="eleves.organisme",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "prises_en_charge_organisme",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="organisme",
            constraint=models.UniqueConstraint(
                fields=("tenant", "nom"), name="uniq_organisme_par_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="priseenchargeorganisme",
            constraint=models.UniqueConstraint(
                fields=("tenant", "eleve", "exercice"),
                name="uniq_pec_organisme_par_eleve_exercice",
            ),
        ),
    ]
