# Generated by Django 5.1 on 2026-07-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0028_organisme_priseenchargeorganisme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleve",
            name="montants_mois",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Montant dû par mois quand il diffère du tarif",
            ),
        ),
    ]
