# Generated by Django 5.1 on 2026-07-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0029_eleve_montants_mois"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="frais_renouvellement",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
