# Generated by Django 5.1 on 2026-09-13 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0030_section_frais_renouvellement"),
        ("tenants", "0012_tenant_anciennete_renouvellement_mois"),
    ]

    operations = [
        migrations.CreateModel(
            name="MouvementEleve",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("SORTIE", "Sortie"),
                            ("REINTEGRATION", "Réintégration"),
                        ],
                        max_length=15,
                    ),
                ),
                ("date_mouvement", models.DateField()),
                (
                    "statut_avant",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "statut_apres",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("motif", models.CharField(blank=True, default="", max_length=300)),
                ("mois_retires", models.JSONField(blank=True, default=list)),
                (
                    "dette_reconnue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "utilisateur",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mouvements",
                        to="eleves.eleve",
                    ),
                ),
                (
                    "fiche_origine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="eleves.eleve",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "mouvements_eleves",
                "ordering": ["-date_mouvement", "-created_at"],
            },
        ),
    ]
