# Generated by Django 5.1 on 2026-09-16 16:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0031_mouvements_eleves"),
        ("tenants", "0012_tenant_anciennete_renouvellement_mois"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeleCertificat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nom_fichier", models.CharField(max_length=255)),
                ("contenu_b64", models.TextField()),
                (
                    "codes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Codes trouvés dans le modèle au téléversement",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "modeles_certificat",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant",), name="uniq_modele_certificat_par_ecole"
                    )
                ],
            },
        ),
    ]
