# Generated by Django 5.1 on 2026-09-17 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0032_modele_certificat"),
        ("tenants", "0014_telephone_plusieurs_numeros"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="mode_tarif",
            field=models.CharField(
                choices=[("MENSUEL", "Au mois"), ("JOURNEE", "À la journée")],
                default="MENSUEL",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="tarif_demi_journee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="section",
            name="tarif_journee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name="PresenceGarderie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "formule",
                    models.CharField(
                        choices=[("DEMI_JOURNEE", "½ journée"), ("JOURNEE", "Journée")],
                        max_length=12,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                ("saisi_par", models.CharField(blank=True, max_length=150)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presences_garderie",
                        to="eleves.eleve",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "presences_garderie",
                "ordering": ["date"],
                "indexes": [
                    models.Index(fields=["tenant", "date"], name="idx_garderie_jour")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "eleve", "date"),
                        name="uniq_presence_garderie_par_jour",
                    )
                ],
            },
        ),
    ]
