# Generated by Django 5.1 on 2026-09-17 11:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0033_garderie_journee"),
        ("tenants", "0014_telephone_plusieurs_numeros"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleveservice",
            name="premiere_adhesion",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="service",
            name="composition_adhesion",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="service",
            name="premier_mois_a_inscription",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="FormuleSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=100)),
                (
                    "frais_mensualite",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("ordre", models.IntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formules",
                        to="eleves.section",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "formules_section",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="FormuleEleve",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mois_debut", models.PositiveSmallIntegerField()),
                ("saisi_par", models.CharField(blank=True, max_length=150)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formules_eleve",
                        to="eleves.eleve",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "formule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eleves",
                        to="eleves.formulesection",
                    ),
                ),
            ],
            options={
                "db_table": "formules_eleve",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "eleve", "mois_debut"),
                        name="uniq_formule_eleve_par_mois",
                    )
                ],
            },
        ),
    ]
