# Generated by Django 5.1 on 2026-09-17 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0034_formules_et_adhesion_services"),
        ("tenants", "0016_garde_du_soir"),
    ]

    operations = [
        migrations.CreateModel(
            name="GardeSoir",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("heure_depart", models.TimeField()),
                ("tranches", models.PositiveSmallIntegerField()),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("saisi_par", models.CharField(blank=True, max_length=150)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gardes_soir",
                        to="eleves.eleve",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "gardes_soir",
                "ordering": ["date", "heure_depart"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "eleve", "date"),
                        name="uniq_garde_soir_par_jour",
                    )
                ],
            },
        ),
    ]
