# Generated by Django 5.1 on 2026-09-17 18:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0035_garde_du_soir"),
        ("tenants", "0016_garde_du_soir"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleve",
            name="attitudes_particulieres",
            field=models.TextField(
                blank=True, help_text="Attitudes particulières à signaler chez l'enfant"
            ),
        ),
        migrations.AddField(
            model_name="eleve",
            name="champs_perso",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="eleve",
            name="profession_mere",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="eleve",
            name="profession_pere",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="eleve",
            name="residence_mere",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="eleve",
            name="residence_pere",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name="ChampFiche",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("libelle", models.CharField(max_length=120)),
                (
                    "type_champ",
                    models.CharField(
                        choices=[
                            ("TEXTE", "Texte court"),
                            ("TEXTE_LONG", "Texte long"),
                            ("NOMBRE", "Nombre"),
                            ("DATE", "Date"),
                            ("LISTE", "Liste de choix"),
                            ("OUI_NON", "Oui / Non"),
                        ],
                        default="TEXTE",
                        max_length=12,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=list)),
                (
                    "groupe",
                    models.CharField(
                        choices=[
                            ("IDENTITE", "Identité de l'élève"),
                            ("PARENTS", "Parents et tuteur"),
                            ("SANTE", "Santé et comportement"),
                            ("AUTRE", "Autres informations"),
                        ],
                        default="AUTRE",
                        max_length=10,
                    ),
                ),
                ("obligatoire", models.BooleanField(default=False)),
                ("ordre", models.IntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "champs_fiche",
                "ordering": ["groupe", "ordre", "libelle"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "libelle"), name="uniq_champ_fiche_par_ecole"
                    )
                ],
            },
        ),
    ]
