# Generated by Django 5.1 on 2026-09-19 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academique", "0006_classe_section"),
        ("eleves", "0036_champs_fiche_et_modules"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="niveau",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sections",
                to="academique.niveauscolaire",
            ),
        ),
    ]
