# Generated by Django 5.1 on 2026-09-19 12:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0037_section_niveau"),
        ("tenants", "0016_garde_du_soir"),
    ]

    operations = [
        migrations.CreateModel(
            name="Famille",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Identifiant de la famille (FAM-0001)",
                        max_length=20,
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("adresse", models.TextField(blank=True)),
                ("observations", models.TextField(blank=True)),
                ("actif", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "familles",
                "ordering": ["nom"],
            },
        ),
        migrations.AddField(
            model_name="eleve",
            name="famille",
            field=models.ForeignKey(
                blank=True,
                help_text="Foyer payeur commun à la fratrie",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eleves",
                to="eleves.famille",
            ),
        ),
        migrations.CreateModel(
            name="ResponsableFamille",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=200)),
                (
                    "lien",
                    models.CharField(
                        choices=[
                            ("PERE", "Père"),
                            ("MERE", "Mère"),
                            ("TUTEUR", "Tuteur"),
                            ("AUTRE", "Autre"),
                        ],
                        default="PERE",
                        max_length=10,
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("telephone2", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("profession", models.CharField(blank=True, max_length=150)),
                ("residence", models.CharField(blank=True, max_length=200)),
                ("principal", models.BooleanField(default=False)),
                (
                    "famille",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsables",
                        to="eleves.famille",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "responsables_famille",
                "ordering": ["-principal", "nom"],
            },
        ),
        migrations.AddConstraint(
            model_name="famille",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_code_famille_par_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="responsablefamille",
            constraint=models.UniqueConstraint(
                condition=models.Q(("principal", True)),
                fields=("famille",),
                name="un_seul_principal_par_famille",
            ),
        ),
    ]
