# Generated by Django 5.1 on 2026-09-19 14:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0038_famille_eleve_famille_responsablefamille_and_more"),
        ("tenants", "0016_garde_du_soir"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eleve",
            name="prise_en_charge",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ORPHELIN", "Orphelin"),
                    ("HANDICAP", "Handicap"),
                    ("FAMILLE_DEMUNIE", "Famille démunie"),
                    ("FRATRIE", "Réduction fratrie"),
                    ("AUTRE", "Autre"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="BaremeFratrie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rang",
                    models.PositiveSmallIntegerField(
                        help_text="Rang de l'enfant dans la famille (2 = deuxième enfant)"
                    ),
                ),
                (
                    "forme_inscription",
                    models.CharField(
                        choices=[
                            ("POURCENTAGE", "Pourcentage"),
                            ("MONTANT", "Montant fixe (FCFA)"),
                        ],
                        default="POURCENTAGE",
                        max_length=12,
                    ),
                ),
                (
                    "valeur_inscription",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "forme_mensualite",
                    models.CharField(
                        choices=[
                            ("POURCENTAGE", "Pourcentage"),
                            ("MONTANT", "Montant fixe (FCFA)"),
                        ],
                        default="POURCENTAGE",
                        max_length=12,
                    ),
                ),
                (
                    "valeur_mensualite",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "baremes_fratrie",
                "ordering": ["rang"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "rang"), name="uniq_bareme_fratrie_par_rang"
                    )
                ],
            },
        ),
    ]
