# Generated by Django 5.1 on 2026-09-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0039_alter_eleve_prise_en_charge_baremefratrie"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleve",
            name="adresse",
            field=models.CharField(
                blank=True,
                help_text="Domicile de l'élève (quartier, rue…)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="eleve",
            name="classe_precedente",
            field=models.CharField(
                blank=True,
                help_text="Classe fréquentée l'année précédente",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="eleve",
            name="contact_urgence_nom",
            field=models.CharField(
                blank=True,
                help_text="Personne à prévenir en cas d'urgence",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="eleve",
            name="contact_urgence_telephone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="eleve",
            name="etablissement_provenance",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="eleve",
            name="groupe_sanguin",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="eleve",
            name="nationalite",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="eleve",
            name="photo",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Photo d'identité (data URI base64, réduite côté navigateur)",
            ),
        ),
        migrations.AddField(
            model_name="eleve",
            name="redoublant",
            field=models.BooleanField(default=False),
        ),
    ]
