# Generated by Django 5.1 on 2026-09-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0040_fiche_renseignements"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="nb_mensualites",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
