# Generated by Django 5.1 on 2026-09-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0041_section_nb_mensualites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mouvementeleve",
            name="type_mouvement",
            field=models.CharField(
                choices=[
                    ("SORTIE", "Sortie"),
                    ("REINTEGRATION", "Réintégration"),
                    ("ANNULATION", "Sortie annulée (erreur de saisie)"),
                ],
                max_length=15,
            ),
        ),
    ]
