# Generated by Django 5.1 on 2026-10-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0042_mouvement_annulation_sortie"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleve",
            name="passage_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
