# Generated by Django 5.1 on 2026-10-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0043_eleve_passage_le"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleveservice",
            name="montant",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
