# Generated by Django 5.1 on 2026-10-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0044_eleveservice_montant"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleveservice",
            name="mois",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
