# Generated by Django 5.1 on 2026-10-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0045_eleveservice_mois"),
    ]

    operations = [
        migrations.AddField(
            model_name="famille",
            name="contact_urgence_nom",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="famille",
            name="contact_urgence_telephone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="responsablefamille",
            name="precision_lien",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
