# Generated by Django 5.1 on 2026-10-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0046_famille_coordonnees_completes"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleve",
            name="cree_par",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
