# Generated by Django 5.1 on 2026-05-01 20:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0002_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('effectif', models.IntegerField(default=0)),
                ('ordre', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'classes',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('coefficient', models.DecimalField(decimal_places=1, default=1, max_digits=4)),
                ('note_max', models.DecimalField(decimal_places=1, default=20, max_digits=4)),
                ('ordre', models.IntegerField(default=0)),
                ('est_active', models.BooleanField(default=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='academique.classe')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'matieres',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='NiveauScolaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=50)),
                ('code', models.CharField(choices=[('PRESCOLAIRE', 'Préscolaire'), ('ELEMENTAIRE', 'Élémentaire'), ('COLLEGE', 'Collège'), ('LYCEE', 'Lycée')], max_length=20)),
                ('note_max', models.DecimalField(decimal_places=1, default=20, max_digits=4)),
                ('ordre', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'niveaux_scolaires',
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academique.niveauscolaire'),
        ),
        migrations.CreateModel(
            name='TypeEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=50)),
                ('poids', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'types_evaluations',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trimestre', models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], max_length=2)),
                ('date_eval', models.DateField()),
                ('titre', models.CharField(blank=True, max_length=100)),
                ('note_max', models.DecimalField(decimal_places=1, default=20, max_digits=4)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academique.matiere')),
                ('type_eval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academique.typeevaluation')),
            ],
            options={
                'db_table': 'evaluations',
                'ordering': ['date_eval'],
            },
        ),
        migrations.CreateModel(
            name='BulletinCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trimestre', models.CharField(max_length=2)),
                ('annee_scolaire', models.CharField(max_length=10)),
                ('moyenne', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('points', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('rang_matiere', models.IntegerField(null=True)),
                ('appreciation', models.CharField(blank=True, max_length=100)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.eleve')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academique.matiere')),
            ],
            options={
                'db_table': 'bulletins_cache',
                'unique_together': {('tenant', 'eleve', 'matiere', 'trimestre', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('absent', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='eleves.eleve')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academique.evaluation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'notes',
                'unique_together': {('tenant', 'eleve', 'evaluation')},
            },
        ),
    ]
