# Generated by Django 5.1 on 2026-08-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academique", "0003_alter_evaluation_trimestre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="niveauscolaire",
            name="code",
            field=models.CharField(
                choices=[
                    ("PRESCOLAIRE", "Préscolaire"),
                    ("ELEMENTAIRE", "Élémentaire"),
                    ("COLLEGE", "Collège"),
                    ("LYCEE", "Lycée"),
                    ("SUPERIEUR", "Supérieur / BTS"),
                ],
                max_length=20,
            ),
        ),
    ]
