# Generated by Django 5.1 on 2026-09-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academique", "0004_alter_niveauscolaire_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="matiere",
            name="programme",
            field=models.CharField(
                choices=[("FR", "Programme français"), ("AR", "Programme arabe")],
                default="FR",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="typeevaluation",
            name="nom_ar",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
