# Generated by Django 5.1 on 2026-09-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academique", "0007_rattacher_classes_aux_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulletincache",
            name="poids",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True
            ),
        ),
    ]
