# Generated by Django 5.1 on 2026-10-05 00:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academique", "0008_bulletincache_poids"),
        ("tenants", "0020_tenant_agregation_domaines_tenant_format_bulletin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="matiere",
            name="compte_dans_moyenne",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="DomaineMatiere",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=20)),
                (
                    "programme",
                    models.CharField(
                        choices=[
                            ("FR", "Programme français"),
                            ("AR", "Programme arabe"),
                        ],
                        default="FR",
                        max_length=2,
                    ),
                ),
                (
                    "coefficient",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("ordre", models.IntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "domaines_matieres",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.AddField(
            model_name="matiere",
            name="domaine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matieres",
                to="academique.domainematiere",
            ),
        ),
        migrations.CreateModel(
            name="PalierMention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("libelle", models.CharField(max_length=60)),
                ("seuil", models.DecimalField(decimal_places=2, max_digits=5)),
                ("couleur", models.CharField(blank=True, default="", max_length=9)),
                ("badge", models.CharField(blank=True, default="", max_length=20)),
                ("distinction", models.BooleanField(default=False)),
                ("ordre", models.IntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "paliers_mention",
                "ordering": ["-seuil"],
            },
        ),
    ]
