# Generated by Django 5.1 on 2026-03-27 23:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('rccm', models.CharField(blank=True, max_length=50)),
                ('ninea', models.CharField(blank=True, max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'École',
                'db_table': 'tenants',
            },
        ),
    ]
