# Generated by Django 5.1 on 2026-05-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='code_etablissement',
            field=models.CharField(default='ETB', max_length=10),
        ),
    ]
