# Generated by Django 5.1 on 2026-06-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_code_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
