# Generated by Django 5.1 on 2026-06-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='regime_paie',
            field=models.CharField(choices=[('COMPLET', 'Complet (affilié)'), ('SIMPLIFIE', 'Simplifié (non affilié)')], default='COMPLET', max_length=10),
        ),
    ]
