# Generated by Django 5.1 on 2026-06-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_regime_paie'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='periode_scolaire',
            field=models.CharField(choices=[('TRIMESTRE', 'Trimestres'), ('SEMESTRE', 'Semestres')], default='TRIMESTRE', max_length=10),
        ),
    ]
