# Generated by Django 5.1 on 2026-06-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_periode_scolaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='nb_periodes',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='periode_scolaire',
            field=models.CharField(choices=[('TRIMESTRE', 'Trimestre'), ('SEMESTRE', 'Semestre'), ('PERIODE', 'Période')], default='TRIMESTRE', max_length=10),
        ),
    ]
