# Generated by Django 5.1 on 2026-07-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_tenant_nb_periodes_alter_tenant_periode_scolaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="numero_autorisation",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
