# Generated by Django 5.1 on 2026-07-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_tenant_numero_autorisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="config_certificat",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
