# Generated by Django 5.1 on 2026-07-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_tenant_config_certificat"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="dernier_mois_a_inscription",
            field=models.BooleanField(
                default=False,
                help_text="La dernière mensualité est encaissée à l'inscription",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="echeance_mensualite",
            field=models.CharField(
                choices=[
                    ("ANTICIPE", "Avant le mois (paiement d'avance)"),
                    ("DEBUT_MOIS", "Dès le début du mois"),
                    ("FIN_MOIS", "À la fin du mois (paiement à terme échu)"),
                ],
                default="DEBUT_MOIS",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="jour_echeance",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Jour du mois de l'échéance (1 à 28)"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="premier_mois_a_inscription",
            field=models.BooleanField(
                default=False,
                help_text="La 1re mensualité est encaissée à l'inscription",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="rappel_actif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="rappel_jour_debut",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Jour du mois où commencent les rappels (1 à 28)"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="rappel_jour_limite",
            field=models.PositiveSmallIntegerField(
                default=10, help_text="Dernier délai de paiement dans le mois (1 à 28)"
            ),
        ),
    ]
