# Generated by Django 5.1 on 2026-07-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0009_tenant_dernier_mois_a_inscription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="rappel_message",
            field=models.TextField(
                blank=True,
                help_text="Message envoyé. Variables : {eleve} {montant} {ecole} {mois} {limite}",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="sms_actif",
            field=models.BooleanField(
                default=False, help_text="Envoyer réellement les rappels par SMS"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="sms_entetes",
            field=models.JSONField(
                blank=True, default=dict, help_text="En-têtes HTTP (autorisation, etc.)"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="sms_gabarit",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Corps de la requête ({destinataire}, {message})",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="sms_methode",
            field=models.CharField(
                choices=[("POST", "POST"), ("GET", "GET")], default="POST", max_length=6
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="sms_url",
            field=models.URLField(
                blank=True, help_text="URL de l'API SMS du fournisseur"
            ),
        ),
    ]
