# Generated by Django 5.1 on 2026-07-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0010_tenant_rappel_message_tenant_sms_actif_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="libelle_renouvellement",
            field=models.CharField(
                default="Renouvellement",
                help_text="Le mot de l'école : Renouvellement, Réinscription, Droit de rentrée…",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="mois_renouvellement",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Mois (1-12) où le renouvellement devient exigible — vide = dès la rentrée",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="renouvellement_actif",
            field=models.BooleanField(
                default=False,
                help_text="Les anciens élèves doivent un renouvellement, pas l'inscription",
            ),
        ),
    ]
