# Generated by Django 5.1 on 2026-07-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0011_tenant_libelle_renouvellement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="anciennete_renouvellement_mois",
            field=models.PositiveSmallIntegerField(
                default=12,
                help_text="Mois de présence à partir desquels l'élève doit un renouvellement",
            ),
        ),
    ]
