# Generated by Django 5.1 on 2026-09-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0012_tenant_anciennete_renouvellement_mois"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="programmes_hybrides",
            field=models.BooleanField(default=False),
        ),
    ]
