# Generated by Django 5.1 on 2026-09-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0014_telephone_plusieurs_numeros"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="directeur_civilite",
            field=models.CharField(
                blank=True, choices=[("M", "Monsieur"), ("MME", "Madame")], max_length=3
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="directeur_nom",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
