# Generated by Django 5.1 on 2026-09-17 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0015_directeur_signataire"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="garde_soir_actif",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenant",
            name="garde_soir_facturation_a",
            field=models.TimeField(default=datetime.time(17, 45)),
        ),
        migrations.AddField(
            model_name="tenant",
            name="garde_soir_heure_limite",
            field=models.TimeField(default=datetime.time(17, 30)),
        ),
        migrations.AddField(
            model_name="tenant",
            name="garde_soir_tarif",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
