# Generated by Django 5.1 on 2026-09-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0016_garde_du_soir"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="bareme_moyenne",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="calcul_moyenne",
            field=models.CharField(
                choices=[
                    ("MATIERES", "Moyenne des matières"),
                    ("POINTS", "Total des points / total des barèmes"),
                ],
                default="MATIERES",
                max_length=10,
            ),
        ),
    ]
