# Generated by Django 5.1 on 2026-09-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0017_tenant_bareme_moyenne_tenant_calcul_moyenne"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="arrondi_moyenne",
            field=models.CharField(
                choices=[
                    ("ARRONDI", "Arrondi au plus proche"),
                    ("TRONQUE", "Tronqué (comme à la main)"),
                ],
                default="ARRONDI",
                max_length=10,
            ),
        ),
    ]
