# Generated by Django 5.1 on 2026-09-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0018_tenant_arrondi_moyenne"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="inspection_academie",
            field=models.CharField(
                blank=True,
                help_text="Inspection d'Académie (IA), ex. Rufisque",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="inspection_ief",
            field=models.CharField(
                blank=True,
                help_text="Inspection de l'Éducation et de la Formation (IEF), ex. Sangalkam",
                max_length=100,
            ),
        ),
    ]
