# Generated by Django 5.1 on 2026-10-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0019_tutelle_academique"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="agregation_domaines",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenant",
            name="format_bulletin",
            field=models.CharField(
                choices=[
                    ("DEMI_A4", "Deux par feuille (A4 couchée)"),
                    ("A4", "Une page A4 par élève (paginée)"),
                ],
                default="DEMI_A4",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="mode_classement",
            field=models.CharField(
                choices=[
                    ("CLASSIQUE", "Classement classique (rangs)"),
                    ("AUCUN", "Aucun classement"),
                    ("MENTIONS", "Mentions et distinctions"),
                ],
                default="CLASSIQUE",
                max_length=10,
            ),
        ),
    ]
