# Generated by Django 5.1 on 2026-10-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0020_tenant_agregation_domaines_tenant_format_bulletin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="recus_services_separes",
            field=models.BooleanField(
                default=False, help_text="Scolarité et services sur des reçus distincts"
            ),
        ),
    ]
