# Generated by Django 5.1 on 2026-03-27 23:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.CharField(max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('solde_initial_caisse', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('solde_initial_banque', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('solde_initial_mobile', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('cloture', models.BooleanField(default=False)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'exercices',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_piece', models.CharField(max_length=30, unique=True)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('montant_inscription', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_mensualite', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_uniforme', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_fournitures', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_cantine', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_divers', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('ESPECE', 'Espèce'), ('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('FREE_MONEY', 'Free Money'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque')], default='ESPECE', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='eleves.eleve')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='paiements.exercice')),
            ],
            options={
                'db_table': 'paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
