# Generated by Django 5.1 on 2026-06-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0003_paiement_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='nb_mensualites',
            field=models.IntegerField(default=10),
        ),
    ]
