# Generated by Django 5.1 on 2026-06-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0004_exercice_nb_mensualites'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='mois_regles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
