# Generated by Django 5.1 on 2026-06-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0005_paiement_mois_regles'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='services_regles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
