# Generated by Django 5.2.13 on 2026-06-28 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0010_eleve_classe'),
        ('paiements', '0006_paiement_services_regles'),
        ('tenants', '0006_tenant_nb_periodes_alter_tenant_periode_scolaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='no_piece',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.UniqueConstraint(fields=('tenant', 'no_piece'), name='uniq_no_piece_par_tenant'),
        ),
    ]
