# Generated by Django 5.1 on 2026-07-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0007_alter_paiement_no_piece_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('ESPECE', 'Espèce'), ('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('FREE_MONEY', 'Free Money'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque'), ('REPRISE', 'Reprise (migration)')], default='ESPECE', max_length=20),
        ),
    ]
