# Generated by Django 5.1 on 2026-07-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paiements", "0008_alter_paiement_mode_paiement"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="modes_reglement",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="mode_paiement",
            field=models.CharField(
                choices=[
                    ("ESPECE", "Espèce"),
                    ("WAVE", "Wave"),
                    ("ORANGE_MONEY", "Orange Money"),
                    ("FREE_MONEY", "Free Money"),
                    ("VIREMENT", "Virement"),
                    ("CHEQUE", "Chèque"),
                    ("MIXTE", "Multi-mode"),
                    ("REPRISE", "Reprise (migration)"),
                ],
                default="ESPECE",
                max_length=20,
            ),
        ),
    ]
