# Generated by Django 5.1 on 2026-07-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paiements", "0009_paiement_modes_reglement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="montant_reliquat",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
