# Generated by Django 5.1 on 2026-07-28 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0028_organisme_priseenchargeorganisme_and_more"),
        ("paiements", "0010_paiement_montant_reliquat"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="organisme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paiements",
                to="eleves.organisme",
            ),
        ),
    ]
