# Generated by Django 5.1 on 2026-08-21 00:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paiements", "0011_paiement_organisme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiement",
            name="date_paiement",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
