# Generated by Django 5.1 on 2026-09-17 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0014_caisses_encaissement"),
        ("paiements", "0012_alter_paiement_date_paiement"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="caisse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paiements",
                to="comptabilite.caisseencaissement",
            ),
        ),
    ]
