# Generated by Django 5.1 on 2026-09-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paiements", "0013_caisses_encaissement"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="part_accessoire",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
