# Generated by Django 5.1 on 2026-09-19 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0039_alter_eleve_prise_en_charge_baremefratrie"),
        ("paiements", "0014_part_accessoire"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="payeur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paiements",
                to="eleves.responsablefamille",
            ),
        ),
        migrations.AddField(
            model_name="paiement",
            name="reference_groupe",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Versement groupé d'une famille",
                null=True,
            ),
        ),
    ]
