# Generated by Django 5.1 on 2026-09-21 16:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleves", "0039_alter_eleve_prise_en_charge_baremefratrie"),
        ("paiements", "0015_paiement_payeur_paiement_reference_groupe"),
        ("tenants", "0016_garde_du_soir"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proforma",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(max_length=30)),
                ("annee_scolaire", models.CharField(max_length=20)),
                ("beneficiaire", models.CharField(blank=True, max_length=200)),
                ("matricule", models.CharField(blank=True, max_length=30)),
                ("section_nom", models.CharField(blank=True, max_length=100)),
                ("formule_nom", models.CharField(blank=True, max_length=100)),
                ("parent_nom", models.CharField(blank=True, max_length=200)),
                ("parent_telephone", models.CharField(blank=True, max_length=60)),
                (
                    "date_emission",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("date_validite", models.DateField()),
                ("lignes", models.JSONField(default=list)),
                ("echeancier", models.JSONField(blank=True, default=list)),
                (
                    "total_du",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "deja_regle",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "part_organisme",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("organisme_nom", models.CharField(blank=True, max_length=200)),
                ("remise_libelle", models.CharField(blank=True, max_length=150)),
                (
                    "remise_montant",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_a_payer",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("parametres", models.JSONField(blank=True, default=dict)),
                ("observations", models.TextField(blank=True)),
                ("conditions", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[("EMISE", "Émise"), ("ANNULEE", "Annulée")],
                        default="EMISE",
                        max_length=10,
                    ),
                ),
                ("motif_annulation", models.CharField(blank=True, max_length=255)),
                ("emise_par", models.CharField(blank=True, max_length=150)),
                (
                    "eleve",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proformas",
                        to="eleves.eleve",
                    ),
                ),
                (
                    "exercice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proformas",
                        to="paiements.exercice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "proformas_scolarite",
                "ordering": ["-date_emission", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "numero"), name="uniq_proforma_par_tenant"
                    )
                ],
            },
        ),
    ]
