# Generated by Django 5.1 on 2026-10-05 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paiements", "0016_proforma_scolarite"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercice",
            name="an_genere_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercice",
            name="an_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="paiements.exercice",
            ),
        ),
    ]
