# Generated by Django 5.1 on 2026-10-08 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paiements", "0017_exercice_an_genere_le_exercice_an_source"),
        ("tenants", "0021_tenant_recus_services_separes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receveur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=100)),
                ("actif", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "receveurs",
                "ordering": ["nom"],
            },
        ),
        migrations.AddField(
            model_name="paiement",
            name="receveur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paiements",
                to="paiements.receveur",
            ),
        ),
        migrations.AddConstraint(
            model_name="receveur",
            constraint=models.UniqueConstraint(
                fields=("tenant", "nom"), name="uniq_receveur_nom_par_ecole"
            ),
        ),
    ]
