from django.urls import path
from .views import (ProjetView, PieceJustificativeView,
                    TransfertView, CanauxTresorerieView,
                    RessourceView, RessourceTracabiliteView, AffectationView,
                    ProjetTracabiliteView, TracabiliteGlobaleView, DashboardGouvernanceView,
                    ProvisionView, ProvisionRepriseView,
                    CompteBancaireView, RapprochementView, LigneReleveView,
                    RapprochementAutoView, RegularisationView, RapprochementValiderView)

urlpatterns = [
    path('projets/',           ProjetView.as_view()),
    path('projets/<uuid:pk>/', ProjetView.as_view()),
    path('projets/<uuid:pk>/tracabilite/', ProjetTracabiliteView.as_view()),
    path('tracabilite/',       TracabiliteGlobaleView.as_view()),
    path('dashboard/',         DashboardGouvernanceView.as_view()),
    path('pieces/',            PieceJustificativeView.as_view()),
    path('pieces/<uuid:pk>/',  PieceJustificativeView.as_view()),
    path('canaux/',            CanauxTresorerieView.as_view()),
    path('transferts/',        TransfertView.as_view()),
    path('transferts/<uuid:pk>/', TransfertView.as_view()),
    path('ressources/',                     RessourceView.as_view()),
    path('ressources/<uuid:pk>/',           RessourceView.as_view()),
    path('ressources/<uuid:pk>/tracabilite/', RessourceTracabiliteView.as_view()),
    path('affectations/',                   AffectationView.as_view()),
    path('affectations/<uuid:pk>/',         AffectationView.as_view()),
    path('provisions/',                     ProvisionView.as_view()),
    path('provisions/<uuid:pk>/',           ProvisionView.as_view()),
    path('provisions/<uuid:pk>/reprise/',   ProvisionRepriseView.as_view()),
    # Rapprochement bancaire (Lot 5)
    path('comptes-bancaires/',              CompteBancaireView.as_view()),
    path('comptes-bancaires/<uuid:pk>/',    CompteBancaireView.as_view()),
    path('rapprochements/',                 RapprochementView.as_view()),
    path('rapprochements/<uuid:pk>/',       RapprochementView.as_view()),
    path('rapprochements/<uuid:pk>/auto/',  RapprochementAutoView.as_view()),
    path('rapprochements/<uuid:pk>/valider/', RapprochementValiderView.as_view()),
    path('rapprochements/<uuid:pk>/lignes/', LigneReleveView.as_view()),
    path('rapprochements/<uuid:pk>/lignes/<uuid:lid>/', LigneReleveView.as_view()),
    path('rapprochements/<uuid:pk>/lignes/<uuid:lid>/regulariser/', RegularisationView.as_view()),
]
