# Generated by Django 5.1 on 2026-03-27 23:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_piece', models.CharField(max_length=30)),
                ('date_ecriture', models.DateField()),
                ('no_compte', models.CharField(max_length=20)),
                ('libelle', models.TextField()),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('source', models.CharField(blank=True, max_length=20)),
                ('source_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'journal_entries',
                'ordering': ['date_ecriture', 'no_piece'],
            },
        ),
    ]
