# Generated by Django 5.1 on 2026-05-18 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0004_journalentry_ordre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['date_ecriture', 'no_piece', 'ordre']},
        ),
    ]
