# Generated by Django 5.1 on 2026-05-21 00:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0006_plan_comptable_budget'),
        ('tenants', '0002_tenant_code_etablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetligne',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='comptecomptable',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='Immobilisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_bien', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=200)),
                ('date_entree', models.DateField()),
                ('valeur_entree', models.DecimalField(decimal_places=2, max_digits=15)),
                ('duree_utilisation', models.IntegerField(help_text='Années')),
                ('mode_amortissement', models.CharField(choices=[('LINEAIRE', 'Linéaire'), ('DEGRESSIF', 'Dégressif')], default='LINEAIRE', max_length=10)),
                ('no_compte_immobilisation', models.CharField(default='231', max_length=10)),
                ('no_compte_amortissement', models.CharField(default='2831', max_length=10)),
                ('cumul_amortissements', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('est_cede', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'immobilisations',
                'ordering': ['date_entree', 'no_bien'],
            },
        ),
    ]
