# Generated by Django 5.1 on 2026-07-22 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0008_immobilisation_reglement"),
        ("gouvernance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="projet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ecritures",
                to="gouvernance.projet",
            ),
        ),
    ]
