# Generated by Django 5.1 on 2026-07-22 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0009_journalentry_projet"),
        ("gouvernance", "0003_ressource_affectationressource_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="ressource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ecritures",
                to="gouvernance.ressource",
            ),
        ),
    ]
