# Generated by Django 5.1 on 2026-07-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0010_journalentry_ressource"),
        ("gouvernance", "0003_ressource_affectationressource_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="immobilisation",
            name="projet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="immobilisations",
                to="gouvernance.projet",
            ),
        ),
        migrations.AddField(
            model_name="immobilisation",
            name="ressource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="immobilisations",
                to="gouvernance.ressource",
            ),
        ),
    ]
