# Generated by Django 5.1 on 2026-07-24 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0011_immobilisation_projet_immobilisation_ressource"),
        ("gouvernance", "0006_alter_piecejustificative_objet_type"),
        ("paiements", "0009_paiement_modes_reglement_and_more"),
        ("tenants", "0008_tenant_config_certificat"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="budgetligne",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="budgetligne",
            name="projet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budget_lignes",
                to="gouvernance.projet",
            ),
        ),
        migrations.AddField(
            model_name="budgetligne",
            name="ressource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budget_lignes",
                to="gouvernance.ressource",
            ),
        ),
        migrations.AddConstraint(
            model_name="budgetligne",
            constraint=models.UniqueConstraint(
                fields=("tenant", "exercice", "no_compte", "projet"),
                name="uniq_budget_compte_projet",
            ),
        ),
    ]
