# Generated by Django 5.1 on 2026-07-30 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "comptabilite",
            "0012_alter_budgetligne_unique_together_budgetligne_projet_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budgetligne",
            options={"ordering": ["no_compte", "libelle"]},
        ),
        migrations.RemoveConstraint(
            model_name="budgetligne",
            name="uniq_budget_compte_projet",
        ),
        migrations.AddField(
            model_name="budgetligne",
            name="mode_realise",
            field=models.CharField(
                choices=[
                    ("COMPTE", "Tout ce qui passe sur ce compte"),
                    ("IMPUTATION", "Seulement les charges rattachées à cette ligne"),
                    ("PAIE", "Seulement la paie"),
                ],
                default="COMPTE",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="budget_ligne",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ecritures",
                to="comptabilite.budgetligne",
            ),
        ),
    ]
