# Generated by Django 5.1 on 2026-09-17 23:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0013_alter_budgetligne_options_and_more"),
        ("tenants", "0016_garde_du_soir"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaisseEncaissement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=100)),
                ("no_compte", models.CharField(max_length=10)),
                ("actif", models.BooleanField(default=True)),
                ("ordre", models.IntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "caisses_encaissement",
                "ordering": ["ordre", "nom"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "no_compte"),
                        name="uniq_caisse_compte_par_ecole",
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "nom"), name="uniq_caisse_nom_par_ecole"
                    ),
                ],
            },
        ),
    ]
