# Generated by Django 5.1 on 2026-10-01 15:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def reprendre_auteurs(apps, schema_editor):
    """Les écritures passées n'avaient pas d'auteur. On le retrouve quand la
    trace existe : l'encaissement porte son saisi_par, l'annulation d'un reçu
    son entrée au journal d'audit (« Nom (RÔLE) » — prise seulement si elle ne
    désigne qu'un compte de l'école)."""
    JournalEntry = apps.get_model('comptabilite', 'JournalEntry')
    Paiement = apps.get_model('paiements', 'Paiement')
    AuditLog = apps.get_model('dashboard', 'AuditLog')
    User = apps.get_model('users', 'User')

    for pid, uid in (Paiement.objects.filter(saisi_par__isnull=False)
                     .values_list('id', 'saisi_par_id').iterator()):
        JournalEntry.objects.filter(source='PAIEMENT', source_id=pid,
                                    saisi_par__isnull=True).update(saisi_par_id=uid)

    comptes = {}
    for u in User.objects.all().only('id', 'nom', 'role', 'tenant_id'):
        cle = (u.tenant_id, f"{u.nom} ({u.role})")
        comptes[cle] = None if cle in comptes else u.id      # homonyme : on s'abstient
    for log in AuditLog.objects.filter(action='ANNULER', modele='Paiement').iterator():
        uid = comptes.get((log.tenant_id, log.utilisateur))
        try:
            uuid.UUID(log.objet_id)
        except ValueError:
            continue
        if uid:
            JournalEntry.objects.filter(source='ANNUL_PAIEMENT', source_id=log.objet_id,
                                        saisi_par__isnull=True).update(saisi_par_id=uid)


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0014_caisses_encaissement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("paiements", "0016_proforma_scolarite"),
        ("dashboard", "0001_audit_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="saisi_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(reprendre_auteurs, migrations.RunPython.noop),
    ]
