# Generated by Django 5.1 on 2026-10-05 00:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0015_journal_saisi_par"),
        ("paiements", "0016_proforma_scolarite"),
        ("tenants", "0020_tenant_agregation_domaines_tenant_format_bulletin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20)),
                ("libelle", models.CharField(max_length=150)),
                (
                    "type_activite",
                    models.CharField(
                        choices=[
                            ("ENSEIGNEMENT", "Enseignement"),
                            ("TRANSPORT", "Transport"),
                            ("RESTAURATION", "Restauration"),
                            ("HEBERGEMENT", "Hébergement / internat"),
                            ("PRESTATION", "Prestations externes"),
                            ("FORMATION", "Formation continue"),
                            ("LOCATION", "Location de locaux / matériel"),
                            ("COMMERCE", "Vente (librairie, uniformes…)"),
                            ("AUTRE", "Autre activité"),
                        ],
                        default="AUTRE",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("est_principale", models.BooleanField(default=False)),
                ("compte_produit", models.CharField(default="706", max_length=10)),
                (
                    "compte_charge",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("compte_client", models.CharField(default="4111", max_length=10)),
                (
                    "regime_tva",
                    models.CharField(
                        choices=[
                            ("EXONERE", "Exonérée"),
                            ("TAXABLE", "Soumise à TVA"),
                            ("HORS_CHAMP", "Hors champ"),
                        ],
                        default="EXONERE",
                        max_length=10,
                    ),
                ),
                (
                    "taux_tva",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("ordre", models.IntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "activites",
                "ordering": ["ordre", "libelle"],
            },
        ),
        migrations.AddField(
            model_name="journalentry",
            name="activite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ecritures",
                to="comptabilite.activite",
            ),
        ),
        migrations.CreateModel(
            name="FactureActivite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(blank=True, default="", max_length=30)),
                ("date_facture", models.DateField()),
                ("date_echeance", models.DateField(blank=True, null=True)),
                ("client_nom", models.CharField(max_length=200)),
                (
                    "client_contact",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "client_ninea",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("lignes", models.JSONField(blank=True, default=list)),
                (
                    "montant_ht",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "taux_tva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "montant_tva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "montant_ttc",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "montant_regle",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("VALIDEE", "Validée"),
                            ("PARTIEL", "Partiellement réglée"),
                            ("PAYEE", "Réglée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="BROUILLON",
                        max_length=10,
                    ),
                ),
                ("observations", models.TextField(blank=True, default="")),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                (
                    "activite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factures",
                        to="comptabilite.activite",
                    ),
                ),
                (
                    "exercice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factures_activite",
                        to="paiements.exercice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "factures_activite",
                "ordering": ["-date_facture", "-numero"],
            },
        ),
        migrations.CreateModel(
            name="ReglementFacture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_reglement", models.DateField()),
                ("montant", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("ESPECE", "Espèce"),
                            ("WAVE", "Wave"),
                            ("ORANGE_MONEY", "Orange Money"),
                            ("FREE_MONEY", "Free Money"),
                            ("VIREMENT", "Virement"),
                            ("CHEQUE", "Chèque"),
                        ],
                        default="ESPECE",
                        max_length=15,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=80)),
                ("no_piece", models.CharField(blank=True, default="", max_length=30)),
                ("annule", models.BooleanField(default=False)),
                (
                    "exercice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="paiements.exercice",
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglements",
                        to="comptabilite.factureactivite",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "reglements_facture",
                "ordering": ["date_reglement"],
            },
        ),
        migrations.AddConstraint(
            model_name="activite",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_activite_code_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="factureactivite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("numero", ""), _negated=True),
                fields=("tenant", "numero"),
                name="uniq_facture_activite_numero_tenant",
            ),
        ),
    ]
