# Generated by Django 5.1 on 2026-10-05 00:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "comptabilite",
            "0016_activite_journalentry_activite_factureactivite_and_more",
        ),
        ("paiements", "0017_exercice_an_genere_le_exercice_an_source"),
        ("tenants", "0020_tenant_agregation_domaines_tenant_format_bulletin_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EtafiArchive",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PROVISOIRE", "Provisoire"),
                            ("DEFINITIF", "Définitif"),
                        ],
                        default="PROVISOIRE",
                        max_length=10,
                    ),
                ),
                ("systeme", models.CharField(blank=True, default="", max_length=20)),
                ("contenu_zip", models.BinaryField()),
                ("taille", models.IntegerField(default=0)),
                ("empreinte", models.CharField(blank=True, default="", max_length=64)),
                ("resume", models.JSONField(blank=True, default=dict)),
                ("observations", models.TextField(blank=True, default="")),
                (
                    "exercice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etafi_archives",
                        to="paiements.exercice",
                    ),
                ),
                (
                    "genere_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "etafi_archives",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "exercice", "version"),
                        name="uniq_etafi_version_exercice",
                    )
                ],
            },
        ),
    ]
